/*
 * SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#if !defined(OFDM_DEMOD_CUH_INCLUDED_)
#define OFDM_DEMOD_CUH_INCLUDED_

#include "ofdmCommonFunc.h"

namespace ofdm_demodulate
{

//--------------------------------------------------------------------------------------------------------
// OFDM demodulation

/**
 * @brief dynamic descriptor for OFDM demodulation
 *
 * @param sqrt_N_FFT_inverse: for normalized of fft output, calculated on CPU, used on GPU
 * @param cpInfo: length：2*N_symbol_slot; first N_symbol_slot containes the CP len for each symbol, second N_symbol_slot contains the accumulated CP len including this symbol
 * @param timeDateIn: length controlled by ofdmDemod class, (N_symbol_slot * N_FFT + totalCP) * N_ueLayer or N_bsLayer
 * @param freqDataOut: length controlled by ofdmDemod class, N_symbol_slot * N_sc * N_ueLayer or N_bsLayer
 */

template <typename Tscalar, typename Tcomplex>
struct ofdmDeModDynDescr_t{
    uint N_FFT;
    float sqrt_N_FFT_inverse;
    uint16_t N_symbol_slot;
    uint16_t * cpInfo;
    uint N_sc;
    uint mu;    
    uint16_t N_bsLayer;
    uint16_t N_ueLayer;
    Tcomplex * timeDataIn;
    Tcomplex * freqDataOut;
    uint32_t N_samp_slot;

    // PRACH parameters
    uint32_t preambleSampStart;
    uint32_t preambleSampEnd;
    uint32_t Nfft_RA;
    uint32_t Nrep;
    uint32_t cpLenPrach;
    uint32_t L_RA;
    uint32_t startSC;
    uint32_t Nsamp_oran;
    uint32_t kBar;
};

/**
 * @brief OFDM demodulation class
 * remove CP, perform ofdm demodulation (FFT) using cuFFTdx
 * @todo __half16 not tested
 */

template <typename Tscalar, typename Tcomplex> 
class ofdmDeModulate
{
public:
    /**
     * @brief Construct a new ofdm demodulation object
     * 
     * @param cuphyCarrierPrms carrier info
     * @param timeDataIn GPU memory address of rx time signal with CP, ofdmDemod does not check size
     * @param freqDataOut GPU memory address of rx freq signal after removing CP and fft, ofdmDemod does not check size
     * @param prach indicator for PRACH or not
     * @param perAntSamp per rx-tx pair sample or not, only used to derive genie channel
     * @param strm cuda stream to run ofdm demodulation
     */
    ofdmDeModulate(cuphyCarrierPrms_t * cuphyCarrierPrms, Tcomplex * timeDataIn, Tcomplex * freqDataOut, bool prach, bool perAntSamp, cudaStream_t strm);
    ~ofdmDeModulate();
    ofdmDeModulate(ofdmDeModulate const&) = delete;
    ofdmDeModulate& operator=(ofdmDeModulate const&) = delete;

    /**
     * @brief run kernel to remove CP and perform FFT
     * use N_rxlayer * N_symbol_slot/OFDM_FFTs_PER_BLOCK_CONST_ thread blocks to perform OFDM demodulation (FFT)
     *  thread block dims are auto generated by cuFFTdx
     * @param enableSwapTxRx swap tx and rx
     * @param strm cuda stream to run, recommand be the same with config strm for synchronization
     */
    void run(uint8_t enableSwapTxRx, cudaStream_t strm);

    /**
     * @brief print sample time signals
     * 
     * @param printLen length of samples to print, 10 by defualt
     */
    void printFreqSample(int printLen = 10); 

    /**
     * @brief Get the Freq Data Out object
     * 
     * @return Tcomplex* GPU memory adress for rx freq samples
     */
    Tcomplex * getFreqDataOut() {return m_ofdmDeModdynDescprCpu -> freqDataOut; } 

    /**
     * @brief Save the carrier, tx freq and time data to hdf5 file
     */
     void saveOfdmDemodToH5File(cudaStream_t strm);
private:
    cuphyCarrierPrms_t * m_cuphyCarrierPrms;
    // dynamic descriptors for CPU and GPU
    ofdmDeModDynDescr_t<Tscalar, Tcomplex> * m_ofdmDeModdynDescprCpu;
    ofdmDeModDynDescr_t<Tscalar, Tcomplex> * m_ofdmDeModdynDescprGpu;
    ofdmLaunchCfg_t*    m_pLaunchCfg; // lauch kernel config
    // CP info for CPU and GPU
    uint16_t * m_cpInfoCpu; 
    uint16_t * m_cpInfoGpu;
    uint32_t m_timeDataLenDl, m_timeDataLenUl; // length of rx time samples
    uint32_t m_freqDataLenDl, m_freqDataLenUl; // length of rx freq samples
    uint8_t m_enableSwapTxRx;  // enable swap tx and rx
    // indicator for PRACH
    bool m_prach;

    void determinePrachParam(cuphyCarrierPrms_t* cuphyCarrierPrms);
};

// Explicitly instantiate the template to resovle "undefined functions"
    template class ofdmDeModulate<__half, __half2>;
    template class ofdmDeModulate<float, cuComplex>; 
} // end of namespace ofdm_demodulate

#endif // !defined(OFDM_DEMOD_CUH_INCLUDED_)