---
aerial_sdk_version: 26-1-cubb
ru_emulator:
  ul_core_list: [18]
  ul_srs_core_list: []
  dl_core_list: [19]
  dl_rx_core_list: [68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106]
  nvlog_name: ru
  oam_cell_ctrl_cmd: 1
  low_priority_core: 4
  nics:
  - {nic_interface: '0002:01:00.0'}
  peers:
  - {peerethaddr: '4c:bb:47:e8:b1:78'}
  cell_configs:
  - name: Cell1
    eth: 20:04:9B:9E:27:A3
    eAxC_UL: [32512, 32513, 32514, 32515]
    eAxC_DL: [32512, 32513, 32514, 32515]
    eAxC_prach_list: [32544, 32545, 32546, 32547]
    eAxC_srs_list: [32576, 32577, 32578, 32579]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell2
    eth: 26:04:9D:9E:29:B3
    eAxC_UL: [1, 2, 4, 9]
    eAxC_DL: [1, 2, 4, 9]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [1, 2, 4, 9]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell3
    eth: 20:34:9A:9E:29:B3
    eAxC_UL: [1, 2, 4, 9]
    eAxC_DL: [1, 2, 4, 9]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [1, 2, 4, 9]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell4
    eth: 22:34:9C:9E:29:A3
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell5
    eth: 20:04:9B:9E:27:05
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell6
    eth: 20:04:9B:9E:27:06
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell7
    eth: 20:04:9B:9E:27:07
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell8
    eth: 20:04:9B:9E:27:08
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell9
    eth: 20:04:9B:9E:27:09
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell10
    eth: 20:04:9B:9E:27:0A
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell11
    eth: 20:04:9B:9E:27:0B
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell12
    eth: 20:04:9B:9E:27:0C
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell13
    eth: 20:04:9B:9E:27:0D
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell14
    eth: 20:04:9B:9E:27:0E
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell15
    eth: 20:04:9B:9E:27:0F
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell16
    eth: 20:04:9B:9E:27:10
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell17
    eth: 20:04:9B:9E:27:11
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell18
    eth: 20:04:9B:9E:27:12
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell19
    eth: 20:04:9B:9E:27:13
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  - name: Cell20
    eth: 20:04:9B:9E:27:14
    eAxC_UL: [0, 1, 2, 3]
    eAxC_DL: [0, 1, 2, 3]
    eAxC_prach_list: [5, 6, 7, 10]
    eAxC_srs_list: [0, 1, 2, 3]
    dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
    fs_offset_dl: 0
    exponent_dl: 4
    ref_dl: 0
    ru_type: 3
    peer: 0
    nic: 0
    vlan: 2
    pcp: 7
  tti: 500
  dl_up_sanity_check: 1
  max_sect_stats: 0
  dl_bfw_validation: 1
  ul_bfw_validation: 1
  beamid_validation: 0
  validate_dl_timing: 1
  timing_histogram: 0
  timing_histogram_bin_size: 1000
  dl_approx_validation: 0
  enable_mmimo: 0
  min_ul_cores_per_cell_mmimo: 3
  enable_beam_forming: 1
  enable_cplane_worker_tracing: 0
  dl_warmup_slots: 512
  ul_warmup_slots: 128
  dlc_tb: 0
  fix_beta_dl: 0
  payload_validation: 1
  enable_dl_proc_mt: 0
  aerial_fh_txq_size: 1024
  aerial_fh_rxq_size: 1024
  aerial_fh_tx_request_num: 32
  aerial_fh_dpdk_thread: 17
  aerial_fh_pdump_client_thread: -1
  aerial_fh_accu_tx_sched_res_ns: 500
  aerial_fh_dpdk_file_prefix: ru_emulator
  aerial_fh_per_rxq_mempool: 0
  aerial_fh_cpu_mbuf_pool_size_per_rxq: 32768
  aerial_fh_cpu_mbuf_pool_rx_size: 262144
  aerial_fh_cpu_mbuf_pool_tx_size: 262144
  aerial_fh_split_rx_tx_mempool: 1
  aerial_fh_mtu: 1514
  enable_srs_eaxcid_pacing: 0
  srs_pacing_s3_srs_symbols: 2
  srs_pacing_s4_srs_symbols: 0
  srs_pacing_s5_srs_symbols: 0
  srs_pacing_eaxcids_per_tx_window: 4
  srs_pacing_eaxcids_per_symbol: 64
  debug_u_plane_prints: 0
  debug_u_plane_threshold: 20
  oran_timing_info: {dl_c_plane_timing_delay: 470, dl_c_plane_window_size: 51, ul_c_plane_timing_delay: 336, ul_c_plane_window_size: 51, dl_u_plane_timing_delay: 345, dl_u_plane_window_size: 51, ul_u_plane_tx_offset: 280, ul_u_plane_tx_offset_srs: 1400}
  oran_beam_id_info: {static_beam_id_start: 1, static_beam_id_end: 16527, dynamic_beam_id_start: 16528, dynamic_beam_id_end: 32767}
  enable_precomputed_tx: 1
  ecpri_hdr_cfg_test: {enable: 0, ecpri_hdr_cfg_file: ecpri_hdr_cfg.yaml}
...
