% SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
% SPDX-License-Identifier: Apache-2.0
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
% http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.

%JMJ

function [nComp, errCnt, nTV, detErr] = testCompGenTV_srs(caseSet, compTvMode, subSetMod, relNum)

tic;
if nargin == 0
    caseSet = 'full';
    compTvMode = 'both';
    subSetMod = [0, 1];
    relNum = 10000;
elseif nargin == 1
    compTvMode = 'both';
    subSetMod = [0, 1];
    relNum = 10000;
elseif nargin == 2
    subSetMod = [0, 1];
    relNum = 10000;
elseif nargin == 3
    relNum = 10000;
end

switch compTvMode
    case 'both'
        genTV = 1;
        testCompliance = 1;
    case 'genTV'
        genTV = 1;
        testCompliance = 0;
    case 'testCompliance'
        genTV = 0;
        testCompliance = 1;
    otherwise
        error('compTvMode is not supported...\n');
end


selected_TC = [8001:8999];
if relNum == 2240 % disable all SRS TCs for Rel-22-4
    disabled_TC = [8001:8999];
else
    % TVs generated by BFW are disabled here to prevent resource
    % contentions with CICD generating them in 2 places at once (SRS + BFW)
    % Ideally, better handling of single-write-multiple-read (SWMR) should be
    % supported to resolve contentions automatically
    disabled_TC = [8046,8412,8413,8512:8526,8531,8532,8535:8555,8558,8559:8566];
end
[~,TcIdx] = ismember(disabled_TC, selected_TC);
selected_TC(TcIdx) = [];

compact_TC = [8001:8999];
full_TC = [8001:8999];

if isnumeric(caseSet)
    TcToTest = caseSet;
else
    switch caseSet
        case 'compact'
            TcToTest = intersect(compact_TC,selected_TC);
        case 'full'
            TcToTest = intersect(full_TC,selected_TC);
        case 'selected'
            TcToTest = selected_TC;
        otherwise
            error('caseSet is not supported...\n');
    end
    % Remove disabled TCs - they are generated elsewhere
    TcToTest = setdiff(TcToTest,disabled_TC);
end

% warning for unsupported code multiplexing cases, detection fails
cdm_TC = [8801 8802 8411 8415];
hasCdmTc = ismember(cdm_TC, TcToTest);
if(sum(hasCdmTc))
    fprintf("Warning: %d code multiplexing cases %s used, detection may fail \n", sum(hasCdmTc), num2str(cdm_TC(hasCdmTc), "%d "));
end

USAGE_BEAM_MGMT = 1;
USAGE_CODEBOOK = 2;
USAGE_NON_CODEBOOK = 4;

CFG = {...
   % TC#  rnti  Nap nSym  Nrep sym0 cfgIdx seqId bwIdx cmbSz cmbOffset cs  fPos fShift frqH grpH resType Tsrs  Toffset idxSlot
    8001   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % base TC
    8002  10     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % rnti
    8003   1     2    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % Nap = 2
    8004   1     4    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % Nap = 4
    8005   1     2    2     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % nSym = 2
    8006   1     2    4     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % nSym = 4
    8007   1     2    4     2    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % Nrep = 2
    8008   1     2    4     4    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % Nrep = 4
    8009   1     2    2     2   10     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % sym0
    8010   1     2    4     2    9    63     0    0     2        0      0    0    0      0    0     0      1      0       0; % cfgIdx
    8011   1     2    4     2    9     3    29    0     2        0      0    0    0      0    0     0      1      0       0; % seqId
    8012   1     2    4     2    9     3     0    1     2        0      0    0    0      0    0     0      1      0       0; % bwIdx = 1
    8013   1     2    4     2    9     3     0    2     2        0      0    0    0      0    0     0      1      0       0; % bwIdx = 2
    8014   1     2    4     2    9     3     0    3     2        0      0    0    0      0    0     0      1      0       0; % bwIdx = 3
    8015   1     2    4     2    9     3     0    2     4        0      0    0    0      0    0     0      1      0       0; % cmbSize
    8016   1     2    4     2    9     3     0    2     2        1      0    0    0      0    0     0      1      0       0; % cmbOffset
    8017   1     2    4     2    9     3     0    2     2        1      7    0    0      0    0     0      1      0       0; % cyclic shift
    8018   1     2    4     2    9     3     0    2     2        1      7   20    0      0    0     0      1      0       0; % freqPosition
    8019   1     2    4     2    9     3     0    2     2        1      7   20   15      0    0     0      1      0       0; % freqShift
    8020   1     2    4     2    9     3     0    2     2        1      7   20   15      1    0     0      1      0       0; % freqHopping = 1
    8021   1     2    4     2    9     3     0    2     2        1      7   20   15      2    0     0      1      0       0; % freqHopping = 2
    8022   1     2    4     2    9     3     0    2     2        1      7   20   15      3    0     0      1      0       0; % freqHopping = 3
    8023   1     2    4     2    9     3     0    2     2        1      7   20   15      0    1     0      1      0       0; % grpSeqHopping = 1
    8024   1     2    4     2    9     3     0    2     2        1      7   20   15      0    2     0      1      0       0; % grpSeqHopping = 2
    8025   1     2    4     2    9     3     0    2     2        1      7   20   15      0    1     1     20      5       0; % resourceType, Tsrs, Toffset, even frame (0-based)
    8026   1     2    4     2    9     3     0    2     2        1      7   20   15      0    1     0      1      0       3; % idxSlot  
    8027   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 2 SRS allocations
    8028   1     2    4     2    9    63     0    0     4        0      0    0    0      0    0     0      1      0       0; % 4 combs 4 users, wideband
    8029   1     2    4     2    9    63     0    0     4        0      0    0    0      0    0     0      1      0       0; % 4 combs 4 users, different constants, wideband
    8030   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 5 users frequency multiplexed
    8031   1     2    4     2    9     3     0    2     2        1      7   20    0      0    0     0      1      0       0; % 5 users frequency multiplexed, hopping
    8032   1     2    1     1    9    63     0    0     4        0      0    0    0      0    0     0      1      0       0; % 4 users wideband. Time multiplexed.
    8033   1     2    1     1    9    63     0    0     4        0      0    0    0      0    0     0      1      0       0; % 16 users wideband. Time and comb multiplexed.
    8034   0     2    4     2    9     3     0    2     2        1      7   20   15      0    1     1     20      5       0; % resourceType, Tsrs, Toffset, odd frame (0-based)
    8035   1     4    1     1   13    63     0    0     4        0      0    0    0      0    0     0      1      0       0; % 16 users wideband. Time and comb multiplexed. USAGE_BEAM_MGMT
    8036   1     4    1     1   13    63     0    0     4        0      0    0    0      0    0     0      1      0       0; % 16 users wideband. Time and comb multiplexed. Usage = 0
    8037   1     4    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % Nap = 4, 1 PRB per PRBG
    8038   1     2    4     4    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % Nrep = 4, 1 PRB per PRBG
    8039   1     2    4     2    9     3     0    2     2        1      7   20   15      3    0     0      1      0       0; % freqHopping = 3, 1 PRB per PRBG
    8040   1     2    4     2    9     3     0    2     2        1      7   20   15      0    2     0      1      0       0; % grpSeqHopping = 2, 1 PRB per PRBG
    8041   1     4    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % Nap = 4, 4 PRBs per PRBG
    8042   1     2    4     4    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % Nrep = 4, 4 PRBs per PRBG
    8043   1     2    4     2    9     3     0    2     2        1      7   20   15      3    0     0      1      0       0; % freqHopping = 3, 4 PRBs per PRBG
    8044   1     2    4     2    9     3     0    2     2        1      7   20   15      0    2     0      1      0       0; % grpSeqHopping = 2, 4 PRBs per PRBG
    8045   1     2    1     1    9    63     0    0     4        0      0    0    0      0    0     0      1      0       0; % 4 users wideband. Time multiplexed. Heterogeneous PRG size
    8046   30    4    1     1    9    63     1    0     4        1      0    0    0      0    0     0      1      0       0; % TC8512 + SRS PRG size = 16
   % Multiple parameters
   % TC#  rnti  Nap nSym  Nrep sym0 cfgIdx seqId bwIdx cmbSz cmbOffset cs  fPos fShift frqH grpH resType Tsrs  Toffset idxSlot
    8051  17     1    1     1   13     1     3    3     2        0      1    3    1      2    0     0      1      0       3;
    8052  11     2    4     2    9    63     1    1     2        1      2    1    3      0    2     0      1      0       1; 
    8053  13     4    2     1   12    63     2    2     4        2      7    2    2      1    1     0      1      0       0; 
    8054  17     1    1     1   13     1     3    3     2        1      1    3    1      2    0     2     20      7       0; % USAGE_NON_CODEBOOK
    8055  13     4    4     1    9    13     3    2     4        2      7    2    6      1    1     0      1      0       0; % USAGE_NON_CODEBOOK
    8056  13     4    4     1    9    13     2    3     4        3      2    7    5      3    2     0      1      0       0; % USAGE_NON_CODEBOOK
    8057  13     4    4     1    9    13     0    3     4        0      0    0    0      0    0     0      1      0       0; % USAGE_NON_CODEBOOK
    8058   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 2 UEs on 2-comb. 1/1         AP.   
    8059   1     2    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 2 UEs on 2-comb. 2/2         AP.   
    8060   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 3 UEs on 2-comb. 1/2/1       AP.    
    8061   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 4 UEs on 2-comb. 1/1/1/1     AP.    
    8062   1     4    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 2 UEs on 2-comb. 4/4         AP.    
    8063   1     2    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 2 UEs on 4-comb. 2/2         AP.    
    8064   1     2    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 3 UEs on 4-comb. 2/2/2       AP.  
    8065   1     4    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 3 UEs on 4-comb. 4/4/4       AP.   
    8066   1     1    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 4 UEs on 4-comb. 1/1/1/1     AP.   
    8067   1     2    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 3 UEs on 4-comb. 2/1/1       AP.  
    8068   1     1    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 2 UEs on 4-comb. 1/1         AP. 
    8069   1     2    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 2 UEs on 4-comb. 2/1         AP. 
    8070   1     1    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 5 UEs on 4-comb. 1/1/1/1/1   AP.
    8071   1     1    1     1    9    63     0    0     4        0      0    0    0      0    0     0      1      0       0; % 2 UEs on 4-comb. 1/1         AP. TEST: 272 PRBS. 
    8072   1     1    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 2 UEs on 4-comb. 1/1         AP. TEST: 64 ANTS.
    8073   1     2    4     2    9     0     0    2     2        1      0   20   15      2    0     0      1      0       0; % 2 UEs on 2-comb. 2/2         AP. TEST: Repitition.
    8074   1     2    4     2    9     4     0    2     2        1      0   20    0      1    0     0      1      0       0; % 2 UEs on 2-comb. 2/2         AP. TEST: Frequency hopping.
    8075   1     1    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 12 UEs on 4-comb. all 1      AP.
    8076   1     1    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 10 UEs on 4-comb. all 1      AP.
    8077   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 2  UEs on 2-comb. 1/1        AP. Different delay offsets.
    8078   1     1    1     1    9    63     0    0     2        0      0    0    0      0    0     0      1      0       0; % 2  UEs on 2-comb. 1/1        AP. Different delay offsets. 272 PRBS.
    8079   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 4  UEs on 2-comb. 1/1/1/1    AP. Different delay offsets.
    8080   1     1    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 2  UEs on 4-comb. 1/1        AP. Different delay offsets.
    8081   1     1    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 4  UEs on 4-comb. 1/1/1/1    AP. Different delay offsets.
    8082   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 2  UEs on 2-comb. 1/1        AP. Different channel gains.  
    8083   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 4  UEs on 2-comb. 1/1/1/1    AP. Different channel gains.
    8084   1     1    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 2  UEs on 4-comb. 1/1        AP. Different channel gains.
    8085   1     1    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 4  UEs on 4-comb. 1/1/1/1    AP. Different channel gains.
    8086   1     1    4     2    9     4     0    2     2        1      0   20    0      1    0     0      1      0       0; % 2  UEs on 2-comb. 1/1        AP. TEST: Frequency hopping/different gains/different delays
    8087   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 8  UEs on 2-comb. all 1      AP. TEST: 64 ANTS (MEMORY STRESS TEST)
    8088   1     1    1     1    9     0     0    0     4        0      0    0    0      0    0     0      1      0       0; % 12 UEs on 2-comb. all 1      AP. TEST: 64 ANTS (MEMORY STRESS TEST)

   % Sweep all cfgIdx
   % TC#  rnti  Nap nSym  Nrep sym0 cfgIdx seqId bwIdx cmbSz cmbOffset cs  fPos fShift frqH grpH resType Tsrs  Toffset idxSlot
    8101  17     1    1     1   13     0     3    0     2        0      0    0    0      0    0     0      1      0       0;
    8102  17     2    1     1   13     1     3    1     4        0      1    0    1      0    1     0      1      0       0;
    8103  17     4    1     1   13     2     3    2     2        1      2    0    2      0    2     0      1      0       0;
    8104  17     1    2     1   12     3     3    3     4        1      3    0    3      0    0     0      1      0       0;
    8105  17     2    2     1   12     4     3    0     2        0      4    3    4      1    1     0      1      0       0;
    8106  17     4    2     1   12     5     3    1     4        0      5    3    5      1    2     0      1      0       0;
    8107  17     1    4     1   10     6     3    2     2        1      6    3    6      1    0     0      1      0       0;
    8108  17     2    4     1   10     7     3    3     4        1      7    3    7      1    1     0      1      0       0;
    8109  17     4    4     1   10     8     3    0     2        0      0    6    8      2    2     0      1      0       0;
    8110  17     1    1     1   13     9     3    1     4        0      1    6    9      2    0     0      1      0       0;
    8111  17     2    1     1   13    10     3    2     2        1      2    6    0      2    1     0      1      0       0;
    8112  17     4    1     1   13    11     3    3     4        1      3    6    1      2    2     0      1      0       0;
    8113  17     1    2     2   12    12     3    0     2        0      4    9    2      3    0     0      1      0       0;
    8114  17     2    2     2   12    13     3    1     4        0      5    9    3      3    1     0      1      0       0;
    8115  17     4    2     2   12    14     3    2     2        1      6    9    4      3    2     0      1      0       0;
    8116  17     1    4     2   10    15     3    3     4        1      7    9    5      3    0     0      1      0       0;
    8117  17     2    4     2   10    16     3    0     2        0      0    1    6      0    1     0      1      0       0;
    8118  17     4    4     2   10    17     3    1     4        0      1    1    7      0    2     0      1      0       0;
    8119  17     1    1     1   13    18     3    2     2        1      2    1    8      0    0     0      1      0       0;
    8120  17     2    1     1   13    19     3    3     4        1      3    1    9      0    1     0      1      0       0;
    8121  17     4    1     1   13    20     3    0     2        0      4    4    0      1    2     0      1      0       0;
    8122  17     1    2     1   12    21     3    1     4        0      5    4    1      1    0     0      1      0       0;
    8123  17     2    2     1   12    22     3    2     2        1      6    4    2      1    1     0      1      0       0;
    8124  17     4    2     1   12    23     3    3     4        1      7    4    3      1    2     0      1      0       0;
    8125  17     1    4     4   10    24     3    0     2        0      0    7    4      2    0     0      1      0       0;
    8126  17     2    4     4   10    25     3    1     4        0      1    7    5      2    1     0      1      0       0;
    8127  17     4    4     4   10    26     3    2     2        1      2    7    6      2    2     0      1      0       0;
    8128  17     1    1     1   13    27     3    3     4        1      3    7    7      2    0     0      1      0       0;
    8129  17     2    1     1   13    28     3    0     2        0      4    2    8      3    1     0      1      0       0;
    8130  17     4    1     1   13    29     3    1     4        0      5    2    9      3    2     0      1      0       0;
    8131  17     1    2     1   12    30     3    2     2        1      6    2    0      3    0     0      1      0       0;
    8132  17     2    2     1   12    31     3    3     4        1      7    2    1      3    1     0      1      0       0;
    8133  17     1    1     1   13    32     3    0     2        0      0    0    0      0    0     0      1      0       0;
    8134  17     2    1     1   13    33     3    1     4        0      1    0    1      0    1     0      1      0       0;
    8135  17     4    1     1   13    34     3    2     2        1      2    0    2      0    2     0      1      0       0;
    8136  17     1    2     1   12    35     3    3     4        1      3    0    3      0    0     0      1      0       0;
    8137  17     2    2     1   12    36     3    0     2        0      4    3    4      1    1     0      1      0       0;
    8138  17     4    2     1   12    37     3    1     4        0      5    3    5      1    2     0      1      0       0;
    8139  17     1    4     1   10    38     3    2     2        1      6    3    6      1    0     0      1      0       0;
    8140  17     2    4     1   10    39     3    3     4        1      7    3    7      1    1     0      1      0       0;
    8141  17     4    4     1   10    40     3    0     2        0      0    6    8      2    2     0      1      0       0;
    8142  17     1    1     1   13    41     3    1     4        0      1    6    9      2    0     0      1      0       0;
    8143  17     2    1     1   13    42     3    2     2        1      2    6    0      2    1     0      1      0       0;
    8144  17     4    1     1   13    43     3    3     4        1      3    6    1      2    2     0      1      0       0;
    8145  17     1    2     2   12    44     3    0     2        0      4    9    2      3    0     0      1      0       0;
    8146  17     2    2     2   12    45     3    1     4        0      5    9    3      3    1     0      1      0       0;
    8147  17     4    2     2   12    46     3    2     2        1      6    9    4      3    2     0      1      0       0;
    8148  17     1    4     2   10    47     3    3     4        1      7    9    5      3    0     0      1      0       0;
    8149  17     2    4     2   10    48     3    0     2        0      0    1    6      0    1     0      1      0       0;
    8150  17     4    4     2   10    49     3    1     4        0      1    1    7      0    2     0      1      0       0;
    8151  17     1    1     1   13    50     3    2     2        1      2    1    8      0    0     0      1      0       0;
    8152  17     2    1     1   13    51     3    3     4        1      3    1    9      0    1     0      1      0       0;
    8153  17     4    1     1   13    52     3    0     2        0      4    4    0      1    2     0      1      0       0;
    8154  17     1    2     1   12    53     3    1     4        0      5    4    1      1    0     0      1      0       0;
    8155  17     2    2     1   12    54     3    2     2        1      6    4    2      1    1     0      1      0       0;
    8156  17     4    2     1   12    55     3    3     4        1      7    4    3      1    2     0      1      0       0;
    8157  17     1    4     4   10    56     3    0     2        0      0    7    4      2    0     0      1      0       0;
    8158  17     2    4     4   10    57     3    1     4        0      1    7    5      2    1     0      1      0       0;
    8159  17     4    4     4   10    58     3    2     2        1      2    7    6      2    2     0      1      0       0;
    8160  17     1    1     1   13    59     3    3     4        1      3    7    7      2    0     0      1      0       0;
    8161  17     2    1     1   13    60     3    0     2        0      4    2    8      3    1     0      1      0       0;
    8162  17     4    1     1   13    61     3    1     4        0      5    2    9      3    2     0      1      0       0;
    8163  17     1    2     1   12    62     3    2     2        1      6    2    0      3    0     0      1      0       0;
    8164  17     2    2     1   12    63     3    3     4        1      7    2    1      3    1     0      1      0       0;
  
   % different BW
   % mu = 1
   % TC#  rnti  Nap nSym  Nrep sym0 cfgIdx seqId bwIdx cmbSz cmbOffset cs  fPos fShift frqH grpH resType Tsrs  Toffset idxSlot
    8201   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 5 MHz
    8202   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 10 MHz
    8203   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 15 MHz
    8204   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 20 MHz
    8205   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 25 MHz
    8206   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 30 MHz
    8207   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 40 MHz
    8208   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 50 MHz
    8209   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 60 MHz
    8210   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 70 MHz
    8211   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 80 MHz
    8212   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 90 MHz
    8213   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 100 MHz
   % mu = 0
    8214   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 5 MHz
    8215   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 10 MHz
    8216   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 15 MHz
    8217   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 20 MHz
    8218   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 25 MHz
    8219   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 30 MHz
    8220   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 40 MHz
    8221   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 50 MHz
   % rx power cases 
    8222   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % +10 dB
    8223   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % -10 dB
    8224   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % +40 dB
    8225   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % -40 dB
    8226   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % forceRxZero 
    % additional BW test cases
    8227   1     1    1     1    9     0     0    0     2        0      0    0    0      0    0     0      1      0       0; % 40 MHz
    
    % integration TCs
    8301   1     1   4     2    9    63     1     0        2   1        0   0    0      0    0     0      1     0       0;   % 1 AP
    8302   2     2   4     2    9    63     1     0        2   1        0   0    0      0    0     0      1     0       0;   % 2 AP (Base case)
    
    % 32 antennas TCs
    % TC#  rnti  Nap nSym  Nrep sym0 cfgIdx seqId bwIdx cmbSz cmbOffset cs  fPos fShift frqH grpH resType Tsrs  Toffset idxSlot
    8401   30     1   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 1 AP (base base)
    8402   31     2   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 2 AP
    8403   32     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 4 AP
    8404   33     1   2     2    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 2 Reps
    8405   34     1   4     4    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 4 Reps
    8406   35     1   1     1    9    63     1     0        4   1        4   0    0      0    0     0      1     0       0; % cs = 4
    8407   36     1   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % Four users, comb muxed
    8408   37     1   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % Four users, time muxed
    8409   38     1   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 16 users, time/comb muxed
    8410   39     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users, 4 AP, time/comb muxed
    8411   40     1   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users, 
    8412   41     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users, 4 AP, time/comb muxed, updated RNTI
    8413   42     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % Four users, comb muxed, updated RNTI
    8414   43     1   1     1    9     3     1     0        4   1        0   0    0      0    0     0      1     0       0; % 16 users, time/comb muxed, varied cfgIdx, fShift
    8415   44     1   1     1    9     3     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users, varied cfgIdx, fShift
    %8416   45     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users, 4 AP, time/comb muxed
    %8417   46     1   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 16 users, time/comb muxed, USAGE_BEAM_MGMT
    %8418   47     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users, 4 AP, time/comb muxed, updated RNTI
    %8419   48     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users, 4 AP, time/comb muxed, updated RNTI
    8420   49     1   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 16 users, 1 AP, time/comb muxed, USAGE_BEAM_MGMT
    8421   50     1   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 16 users, time/comb muxed, MIX USAGE
    
    % TC numbers 85XX reserved for 64 antennas TCs
    % TC#  rnti  Nap nSym  Nrep sym0 cfgIdx seqId bwIdx cmbSz cmbOffset cs  fPos fShift frqH grpH resType Tsrs  Toffset idxSlot
    8501   30     1   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 1 AP (base base)
    8502   30     2   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 2 AP
    8503   30     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 4 AP
    8504   30     1   2     2    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 2 Reps
    8505   30     1   4     4    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 4 Reps
    8506   30     1   1     1    9    63     1     0        4   1        4   0    0      0    0     0      1     0       0; % cs = 4
    8507   30     1   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % Four users, comb muxed
    8508   30     1   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % Four users, time muxed
    8509   30     1   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 16 users, time/comb muxed
    8510   30     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users, 4 AP, time/comb muxed
    8511   30     1   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users, 
    8512   30     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 16 users, 
    8513    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % Four users, comb muxed, updated RNTI
    8514   30     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users, 
    8515    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % Four users, comb muxed, updated RNTI
    8516   30     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users,
    8517    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % Four users, comb muxed, updated RNTI
    8518   30     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users,
    8519    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % Four users, comb muxed, updated RNTI
    8520   30     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users,
    8521    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % Four users, comb muxed, updated RNTI
    8522   30     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users,
    8523    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % Four users, comb muxed, updated RNTI
    8524   30     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users,
    8525    1     4   1     1    9    16     1     0        4   0        0   0  100      0    0     0      1     0       0; % 60 PRBs starting at RB100
    8526    1     4   1     1    9    16     1     0        4   1        0   0  100      0    0     0      1     0       0; % 60 PRBs starting at RB100
    8527    1     4   1     1    9    30     1     1        4   0        0   0  160      0    0     0      1     0       0; % 64 PRBs starting at RB160
    8528   30     4   1     1    9    30     1     1        4   1        0   0  160      0    0     0      1     0       0; % 64 PRBs starting at RB160
    8529    1     4   1     1    9     4     1     3        4   0        0   0   60      0    0     0      1     0       0; %  4 PRBs starting at RB60
    8530   30     4   1     1    9     4     1     3        4   1        0   0   60      0    0     0      1     0       0; %  4 PRBs starting at RB60
    8531    1     4   1     1    9    30     1     1        4   0        0   0  160      0    0     0      1     0       0; % 64 PRBs starting at RB160, prg=4
    8532    2     4   1     1    9    30     1     1        4   1        0   0  160      0    0     0      1     0       0; % 64 PRBs starting at RB160, prg=4
    8533    1     4   1     1    9    27     1     0        4   0        0   0  100      0    0     0      1     0       0; % 120 PRBs starting at RB100, prg=4
    8534   30     4   1     1    9    27     1     0        4   1        0   0  100      0    0     0      1     0       0; % 120 PRBs starting at RB100, prg=4
    8535    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % 8 users, comb muxed
    8536   30     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 8 users, comb muxed, updated RNTI
    8537    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % Four users, comb muxed
    8538   30     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % Four users, comb muxed, updated RNTI
    8539    1     4   1     1    9    30     1     1        4   0        0   0  160      0    0     0      1     0       0; % 64 PRBs starting at RB160 4-layer
    8540   30     4   1     1    9    30     1     1        4   1        0   0  160      0    0     0      1     0       0; % 64 PRBs starting at RB160 8-layer
    8541    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % TBD
    8542    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % TBD
    8543    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % TBD
    8544    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % TBD
    8545    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % TBD
    8546    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % TBD
    8547    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % TBD
    8548    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % TBD
    8549    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % TBD
    8550    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % TBD
    8551    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % TBD
    8552    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % TBD
    8553    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % TBD
    8554    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % TBD    
    8555   30     4   1     1    9    63     1     0        4   1        0   0    0      0    0     0      1     0       0; % 16 users,
    8556    1     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % Four users, comb muxed, updated RNTI
    8557    1     4   1     1    9    30     1     1        4   0        0   0  160      0    0     0      1     0       0; % 64 PRBs starting at RB160, prg=4
    8558    2     4   1     1    9    30     1     1        4   1        0   0  160      0    0     0      1     0       0; % 64 PRBs starting at RB160
    8559   30     1   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % SRS RKHS TEST CASE. 1 ant ports
    8560   30     2   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % SRS RKHS TEST CASE. 2 ant ports
    8561   30     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % SRS RKHS TEST CASE. 4 ant ports
    8562   30     1   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % SRS RKHS TEST CASE. 1 ant ports, prg = 1
    8563   30     2   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % SRS RKHS TEST CASE. 2 ant ports, prg = 1
    8564   30     4   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % SRS RKHS TEST CASE. 4 ant ports, prg = 1
    8565   30     1   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % SRS RKHS TEST CASE. 1 ant ports, SNR = -30
    8566   30     1   1     1    9    63     1     0        4   0        0   0    0      0    0     0      1     0       0; % SRS RKHS TEST CASE. 1 ant ports, SNR = 30


   

    % TC#  rnti  Nap nSym  Nrep sym0 cfgIdx seqId bwIdx cmbSz cmbOffset cs  fPos fShift frqH grpH resType Tsrs  Toffset idxSlot SNR
    % perf TV
    % F09
    8801  17     4    1     1   13    63     0    0     4        0      0    0    0      0    0     0      10     0       0;
    % 20 MHz
    8802  17     4    1     1   12    12     0    0     4        0      0    0    0      0    0     0      1      0       0;
    % F14
    % 8803  17     4    1     1   13    63     0    0     4        0      0    0    0      0    0     0      10     0       0;
    % % 20 MHz
    % 8804  17     4    1     1   12    12     0    0     4        0      0    0    0      0    0     0      1      0       0;
    

    };

[NallTest, ~] = size(CFG);
errCnt = 0;
detErr = 0;
nTV = 0;
nComp = 0;

if (isnumeric(caseSet))
    caseSetStr = num2str(caseSet);
else
    caseSetStr = caseSet;
end
fprintf('SRS: genTV = %d, testCompliance = %d, caseSet = %s', genTV, testCompliance, caseSetStr);
fprintf('\nTC#  rnti  Nap nSym  Nrep sym0 cfgIdx seqId bwIdx cmbSz cmbOffset cs  fPos fShift frqH grpH resType Tsrs  Toffset idxSlot PASS det  SNR snrErrDb toErrUs hestErrDb\n');
fprintf('------------------------------------------------------------------------------------------------------------------------------------------------------------------\n');

parfor n = 1:NallTest
    testAlloc = [];
    testAlloc.dl = 0;
    testAlloc.ul = 1;
    testAlloc.srs = 1;
    idxSet = n;
    caseNum = CFG{idxSet, 1};
    if ismember(caseNum, TcToTest) && (mod(caseNum, subSetMod(2)) == subSetMod(1))
        rng(caseNum);
        SysPar = initSysPar(testAlloc);
        SysPar.SimCtrl.relNum = relNum;        
        SysPar.SimCtrl.N_frame = 1;
        SysPar.Chan{1}.SNR = 20;        
        if genTV
            nTV = nTV + 1;
            SysPar.SimCtrl.genTV.enable = 1;
            SysPar.SimCtrl.genTV.enableUE = 1;
            SysPar.SimCtrl.genTV.slotIdx = CFG{idxSet, 20};
            SysPar.SimCtrl.N_slot_run = CFG{idxSet, 20} + 1;
            SysPar.SimCtrl.genTV.TVname = sprintf('TVnr_%04d', caseNum);
            if ismember(caseNum, disabled_TC)
                % Disabled TVs will not get generated by default (See BFW+SRS contention comment above).  
                % If they are manually generated, they will use the regular naming convetion
%                SysPar.SimCtrl.genTV.TVname = sprintf('disabled_TVnr_%04d', caseNum);
            end
        end
                
        SysPar.srs{1}.RNTI = CFG{idxSet, 2};
        SysPar.srs{1}.numAntPorts = CFG{idxSet, 3};
        SysPar.srs{1}.numSymbols = CFG{idxSet, 4};
        SysPar.srs{1}.numRepetitions = CFG{idxSet, 5};
        SysPar.srs{1}.timeStartPosition = CFG{idxSet, 6};
        SysPar.srs{1}.configIndex = CFG{idxSet, 7};
        SysPar.srs{1}.sequenceId = CFG{idxSet, 8};
        SysPar.srs{1}.bandwidthIndex = CFG{idxSet, 9};
        SysPar.srs{1}.combSize = CFG{idxSet, 10};
        SysPar.srs{1}.combOffset = CFG{idxSet, 11};
        SysPar.srs{1}.cyclicShift = CFG{idxSet, 12};
        SysPar.srs{1}.frequencyPosition = CFG{idxSet, 13};
        SysPar.srs{1}.frequencyShift = CFG{idxSet, 14};
        SysPar.srs{1}.frequencyHopping = CFG{idxSet, 15};
        SysPar.srs{1}.groupOrSequenceHopping = CFG{idxSet, 16};
        SysPar.srs{1}.resourceType = CFG{idxSet, 17};
        SysPar.srs{1}.Tsrs = CFG{idxSet, 18};
        SysPar.srs{1}.Toffset = CFG{idxSet, 19};
        SysPar.srs{1}.usage = USAGE_CODEBOOK;
        
        if SysPar.srs{1}.resourceType > 0
            SysPar.SimCtrl.genTV.slotIdx = SysPar.srs{1}.Toffset;
            SysPar.SimCtrl.N_slot_run = SysPar.SimCtrl.genTV.slotIdx + 1;
        end

        if ismember(caseNum, [8054:8057])
            SysPar.srs{1}.usage = USAGE_NON_CODEBOOK;
        end
        if ismember(caseNum, [8046 8512 8514 8516 8518 8520 8522 8524 8526 8628 8530 8532 8534 8536 8538 8540 8542:2:8554 8558])
            SysPar.srs{1}.usage = USAGE_NON_CODEBOOK;
        end
        if ismember(caseNum, [8513 8515 8517 8519 8521 8523 8525 8527 8529 8531 8533 8535 8537 8539 8541:2:8553 8557])
            SysPar.srs{1}.usage = USAGE_CODEBOOK;
        end
        if ismember(caseNum, [8555])
            SysPar.srs{1}.usage = (USAGE_BEAM_MGMT+USAGE_NON_CODEBOOK);
        end
        if ismember(caseNum, [8556])
            SysPar.srs{1}.usage = (USAGE_BEAM_MGMT+USAGE_CODEBOOK);
        end
        if ismember(caseNum, [8035,8420])
            SysPar.srs{1}.usage = USAGE_BEAM_MGMT;
        end
        
        if ismember(caseNum,[8224 8411])
            SysPar.SimCtrl.alg.srs_chEst_toL2_normalization_algo_selector = 0; 
        end
        
        if caseNum == 8027
            SysPar.srs{2} = SysPar.srs{1};
            SysPar.srs{2}.numAntPorts = 2;
            SysPar.srs{2}.numSymbols = 2;
            SysPar.srs{2}.timeStartPosition = 10;
            SysPar.srs{2}.configIndex = 3;
            SysPar.Chan{2} = SysPar.Chan{1};
            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE = 2;

        elseif ismember(caseNum,[8028 8407 8413 8541 8549 8551])
            SysPar.testAlloc.srs = 4;
            SysPar.SimCtrl.N_UE  = 4;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});
            
            SysPar.srs{2}.combOffset = 1;
            SysPar.srs{3}.combOffset = 2;
            SysPar.srs{4}.combOffset = 3;

        elseif caseNum == 8029
            SysPar.testAlloc.srs = 4;
            SysPar.SimCtrl.N_UE  = 4;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});
            
            SysPar.srs{2}.combOffset = 1;
            SysPar.srs{3}.combOffset = 2;
            SysPar.srs{4}.combOffset = 3;
            
            SysPar.srs{2}.cyclicShift = 1;
            SysPar.srs{3}.cyclicShift = 2;
            SysPar.srs{4}.cyclicShift = 3;
            
            SysPar.srs{2}.groupOrSequenceHopping = 1;
            SysPar.srs{3}.groupOrSequenceHopping = 2;
            SysPar.srs{4}.groupOrSequenceHopping = 1;
            
        elseif caseNum == 8543
            SysPar.testAlloc.srs = 3;
            SysPar.SimCtrl.N_UE  = 3;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});
            
            SysPar.srs{2}.timeStartPosition = 10;
            SysPar.srs{3}.timeStartPosition = 11;
        elseif ismember(caseNum,[8030:8031])
            SysPar.testAlloc.srs = 5;
            SysPar.SimCtrl.N_UE  = 5;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});

            SysPar.srs{2}.frequencyShift = 20;
            SysPar.srs{3}.frequencyShift = 40;
            SysPar.srs{4}.frequencyShift = 60;
            SysPar.srs{5}.frequencyShift = 80;

            
        elseif ismember(caseNum,[8032 8408 8045])
            SysPar.testAlloc.srs = 4;
            SysPar.SimCtrl.N_UE  = 4;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});
            
            SysPar.srs{2}.timeStartPosition = 10;
            SysPar.srs{3}.timeStartPosition = 11;
            SysPar.srs{4}.timeStartPosition = 12;

            if caseNum == 8045
                SysPar.srs{1}.prgSize = 4;
                SysPar.srs{2}.prgSize = 8;
                SysPar.srs{3}.prgSize = 16;
                SysPar.srs{4}.prgSize = 272;
            end

        elseif ismember(caseNum,[8033,8035,8409, 8420])
            SysPar.testAlloc.srs = 16;
            SysPar.SimCtrl.N_UE  = 16;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});
            
            SysPar.srs{1}.timeStartPosition = 9;
            SysPar.srs{2}.timeStartPosition = 9;
            SysPar.srs{3}.timeStartPosition = 9;
            SysPar.srs{4}.timeStartPosition = 9;
            
            SysPar.srs{5}.timeStartPosition = 10;
            SysPar.srs{6}.timeStartPosition = 10;
            SysPar.srs{7}.timeStartPosition = 10;
            SysPar.srs{8}.timeStartPosition = 10;
            
            SysPar.srs{9}.timeStartPosition = 11;
            SysPar.srs{10}.timeStartPosition = 11;
            SysPar.srs{11}.timeStartPosition = 11;
            SysPar.srs{12}.timeStartPosition = 11;
            
            SysPar.srs{13}.timeStartPosition = 12;
            SysPar.srs{14}.timeStartPosition = 12;
            SysPar.srs{15}.timeStartPosition = 12;
            SysPar.srs{16}.timeStartPosition = 12;
            
            SysPar.srs{1}.combOffset = 0;
            SysPar.srs{2}.combOffset = 1;
            SysPar.srs{3}.combOffset = 2;
            SysPar.srs{4}.combOffset = 3;
            
            SysPar.srs{5}.combOffset = 0;
            SysPar.srs{6}.combOffset = 1;
            SysPar.srs{7}.combOffset = 2;
            SysPar.srs{8}.combOffset = 3;
            
            SysPar.srs{9}.combOffset  = 0;
            SysPar.srs{10}.combOffset = 1;
            SysPar.srs{11}.combOffset = 2;
            SysPar.srs{12}.combOffset = 3;

            SysPar.srs{13}.combOffset = 0;
            SysPar.srs{14}.combOffset = 1;
            SysPar.srs{15}.combOffset = 2;
            SysPar.srs{16}.combOffset = 3;
        elseif ismember(caseNum,[8553])
            SysPar.testAlloc.srs = 12;
            SysPar.SimCtrl.N_UE  = 12;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});
            
            SysPar.srs{1}.timeStartPosition = 9;
            SysPar.srs{2}.timeStartPosition = 9;
            SysPar.srs{3}.timeStartPosition = 9;
            SysPar.srs{4}.timeStartPosition = 9;
            
            SysPar.srs{5}.timeStartPosition = 10;
            SysPar.srs{6}.timeStartPosition = 10;
            SysPar.srs{7}.timeStartPosition = 10;
            SysPar.srs{8}.timeStartPosition = 10;
            
            SysPar.srs{9}.timeStartPosition = 11;
            SysPar.srs{10}.timeStartPosition = 11;
            SysPar.srs{11}.timeStartPosition = 11;
            SysPar.srs{12}.timeStartPosition = 11;
            
            SysPar.srs{1}.combOffset = 0;
            SysPar.srs{2}.combOffset = 1;
            SysPar.srs{3}.combOffset = 2;
            SysPar.srs{4}.combOffset = 3;
            
            SysPar.srs{5}.combOffset = 0;
            SysPar.srs{6}.combOffset = 1;
            SysPar.srs{7}.combOffset = 2;
            SysPar.srs{8}.combOffset = 3;
            
            SysPar.srs{9}.combOffset  = 0;
            SysPar.srs{10}.combOffset = 1;
            SysPar.srs{11}.combOffset = 2;
            SysPar.srs{12}.combOffset = 3;

        elseif caseNum == 8034
            SysPar.carrier.SFN_start = 1; % skip the first frame, to be used with TC 8025

        elseif ismember(caseNum, 8037:8040) % 1 PRB per PRBG
            SysPar.srs{1}.prgSize = 1;

        elseif ismember(caseNum, [8041:8044, 8531:8534, 8557]) % 4 PRBs per PRBG
            SysPar.srs{1}.prgSize = 4;

        elseif ismember(caseNum, [8410,8412,8513,8514,8515:8524,8535,8537,8539,8540,8542:2:8556])
            SysPar.testAlloc.srs = 8;
            SysPar.SimCtrl.N_UE  = 8;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});

            SysPar.srs{1}.timeStartPosition = 9;
            SysPar.srs{2}.timeStartPosition = 9;
            SysPar.srs{3}.timeStartPosition = 10;
            SysPar.srs{4}.timeStartPosition = 10;

            SysPar.srs{5}.timeStartPosition = 11;
            SysPar.srs{6}.timeStartPosition = 11;
            SysPar.srs{7}.timeStartPosition = 12;
            SysPar.srs{8}.timeStartPosition = 12;

            SysPar.srs{1}.combOffset = 0;
            SysPar.srs{2}.combOffset = 1;
            SysPar.srs{3}.combOffset = 2;
            SysPar.srs{4}.combOffset = 3;

            SysPar.srs{5}.combOffset = 0;
            SysPar.srs{6}.combOffset = 1;
            SysPar.srs{7}.combOffset = 2;
            SysPar.srs{8}.combOffset = 3;
        elseif ismember(caseNum, [8545])
            SysPar.testAlloc.srs = 6;
            SysPar.SimCtrl.N_UE  = 6;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});

            SysPar.srs{1}.timeStartPosition = 9;
            SysPar.srs{2}.timeStartPosition = 9;
            SysPar.srs{3}.timeStartPosition = 10;
            SysPar.srs{4}.timeStartPosition = 10;
            SysPar.srs{5}.timeStartPosition = 11;
            SysPar.srs{6}.timeStartPosition = 11;

            SysPar.srs{1}.combOffset = 0;
            SysPar.srs{2}.combOffset = 1;
            SysPar.srs{3}.combOffset = 2;
            SysPar.srs{4}.combOffset = 3;

            SysPar.srs{5}.combOffset = 0;
            SysPar.srs{6}.combOffset = 1;
        elseif ismember(caseNum, [8547])
            SysPar.testAlloc.srs = 5;
            SysPar.SimCtrl.N_UE  = 5;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});

            SysPar.srs{1}.timeStartPosition = 9;
            SysPar.srs{2}.timeStartPosition = 9;
            SysPar.srs{3}.timeStartPosition = 10;
            SysPar.srs{4}.timeStartPosition = 10;
            SysPar.srs{5}.timeStartPosition = 11;

            SysPar.srs{1}.combOffset = 0;
            SysPar.srs{2}.combOffset = 1;
            SysPar.srs{3}.combOffset = 2;
            SysPar.srs{4}.combOffset = 3;

            SysPar.srs{5}.combOffset = 0;

        elseif caseNum == 8411
            SysPar.testAlloc.srs = 8;
            SysPar.SimCtrl.N_UE  = 8;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});

            SysPar.srs{1}.numAntPorts = 1;
            SysPar.srs{2}.numAntPorts = 2;
            SysPar.srs{3}.numAntPorts = 2;
            SysPar.srs{4}.numAntPorts = 4;
            SysPar.srs{5}.numAntPorts = 1;
            SysPar.srs{6}.numAntPorts = 4;
            SysPar.srs{7}.numAntPorts = 2;
            SysPar.srs{8}.numAntPorts = 2;

            SysPar.srs{1}.numSymbols = 1;
            SysPar.srs{2}.numSymbols = 2;
            SysPar.srs{3}.numSymbols = 4;
            SysPar.srs{4}.numSymbols = 1;
            SysPar.srs{5}.numSymbols = 2;
            SysPar.srs{6}.numSymbols = 1;
            SysPar.srs{7}.numSymbols = 2;
            SysPar.srs{8}.numSymbols = 1;

            SysPar.srs{1}.timeStartPosition = 10;
            SysPar.srs{2}.timeStartPosition = 10;
            SysPar.srs{3}.timeStartPosition = 10;
            SysPar.srs{4}.timeStartPosition = 11;

            SysPar.srs{5}.timeStartPosition = 11;
            SysPar.srs{6}.timeStartPosition = 12;
            SysPar.srs{7}.timeStartPosition = 12;
            SysPar.srs{8}.timeStartPosition = 13;

            SysPar.srs{1}.combOffset = 0;
            SysPar.srs{2}.combOffset = 1;
            SysPar.srs{3}.combOffset = 2;
            SysPar.srs{4}.combOffset = 3;

            SysPar.srs{5}.combOffset = 0;
            SysPar.srs{6}.combOffset = 1;
            SysPar.srs{7}.combOffset = 2;
            SysPar.srs{8}.combOffset = 3;

            SysPar.srs{1}.cyclicShift = 0;
            SysPar.srs{2}.cyclicShift = 3;
            SysPar.srs{3}.cyclicShift = 6;
            SysPar.srs{4}.cyclicShift = 9;

            SysPar.srs{5}.cyclicShift = 0;
            SysPar.srs{6}.cyclicShift = 3;
            SysPar.srs{7}.cyclicShift = 6;
            SysPar.srs{8}.cyclicShift = 9;

            SysPar.SimCtrl.alg.srs_chEst_toL2_constant_scaler = 8196;

        elseif caseNum == 8414
            SysPar.testAlloc.srs = 16;
            SysPar.SimCtrl.N_UE  = 16;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});
            
            SysPar.srs{1}.timeStartPosition = 9;
            SysPar.srs{2}.timeStartPosition = 9;
            SysPar.srs{3}.timeStartPosition = 9;
            SysPar.srs{4}.timeStartPosition = 9;
            
            SysPar.srs{5}.timeStartPosition = 10;
            SysPar.srs{6}.timeStartPosition = 10;
            SysPar.srs{7}.timeStartPosition = 10;
            SysPar.srs{8}.timeStartPosition = 10;
            
            SysPar.srs{9}.timeStartPosition = 11;
            SysPar.srs{10}.timeStartPosition = 11;
            SysPar.srs{11}.timeStartPosition = 11;
            SysPar.srs{12}.timeStartPosition = 11;
            
            SysPar.srs{13}.timeStartPosition = 12;
            SysPar.srs{14}.timeStartPosition = 12;
            SysPar.srs{15}.timeStartPosition = 12;
            SysPar.srs{16}.timeStartPosition = 12;
            
            SysPar.srs{1}.combOffset = 0;
            SysPar.srs{2}.combOffset = 1;
            SysPar.srs{3}.combOffset = 2;
            SysPar.srs{4}.combOffset = 3;
            
            SysPar.srs{5}.combOffset = 0;
            SysPar.srs{6}.combOffset = 1;
            SysPar.srs{7}.combOffset = 2;
            SysPar.srs{8}.combOffset = 3;
            
            SysPar.srs{9}.combOffset  = 0;
            SysPar.srs{10}.combOffset = 1;
            SysPar.srs{11}.combOffset = 2;
            SysPar.srs{12}.combOffset = 3;

            SysPar.srs{13}.combOffset = 0;
            SysPar.srs{14}.combOffset = 1;
            SysPar.srs{15}.combOffset = 2;
            SysPar.srs{16}.combOffset = 3;

            SysPar.srs{1}.frequencyShift = 0;
            SysPar.srs{2}.frequencyShift = 16;
            SysPar.srs{3}.frequencyShift = 32;
            SysPar.srs{4}.frequencyShift = 48;
            
            SysPar.srs{5}.frequencyShift = 0;
            SysPar.srs{6}.frequencyShift = 16;
            SysPar.srs{7}.frequencyShift = 32;
            SysPar.srs{8}.frequencyShift = 48;
            
            SysPar.srs{9}.frequencyShift  = 0;
            SysPar.srs{10}.frequencyShift = 16;
            SysPar.srs{11}.frequencyShift = 32;
            SysPar.srs{12}.frequencyShift = 48;

            SysPar.srs{13}.frequencyShift = 0;
            SysPar.srs{14}.frequencyShift = 16;
            SysPar.srs{15}.frequencyShift = 32;
            SysPar.srs{16}.frequencyShift = 48;
        
        elseif caseNum == 8415
            SysPar.testAlloc.srs = 8;
            SysPar.SimCtrl.N_UE  = 8;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});

            SysPar.srs{1}.numAntPorts = 1;
            SysPar.srs{2}.numAntPorts = 2;
            SysPar.srs{3}.numAntPorts = 2;
            SysPar.srs{4}.numAntPorts = 4;
            SysPar.srs{5}.numAntPorts = 1;
            SysPar.srs{6}.numAntPorts = 4;
            SysPar.srs{7}.numAntPorts = 2;
            SysPar.srs{8}.numAntPorts = 2;

            SysPar.srs{1}.numSymbols = 1;
            SysPar.srs{2}.numSymbols = 2;
            SysPar.srs{3}.numSymbols = 4;
            SysPar.srs{4}.numSymbols = 1;
            SysPar.srs{5}.numSymbols = 2;
            SysPar.srs{6}.numSymbols = 1;
            SysPar.srs{7}.numSymbols = 2;
            SysPar.srs{8}.numSymbols = 1;

            SysPar.srs{4}.configIndex = 30;

            SysPar.srs{1}.timeStartPosition = 10;
            SysPar.srs{2}.timeStartPosition = 10;
            SysPar.srs{3}.timeStartPosition = 10;
            SysPar.srs{4}.timeStartPosition = 11;   

            SysPar.srs{5}.timeStartPosition = 11;
            SysPar.srs{6}.timeStartPosition = 12;
            SysPar.srs{7}.timeStartPosition = 12;
            SysPar.srs{8}.timeStartPosition = 13;

            SysPar.srs{1}.frequencyShift = 0;
            SysPar.srs{2}.frequencyShift = 16;
            SysPar.srs{3}.frequencyShift = 32;
            SysPar.srs{4}.frequencyShift = 16;
            
            SysPar.srs{5}.frequencyShift = 32;
            SysPar.srs{6}.frequencyShift = 16;
            SysPar.srs{7}.frequencyShift = 0;
            SysPar.srs{8}.frequencyShift = 48;

            SysPar.srs{1}.combOffset = 0;
            SysPar.srs{2}.combOffset = 1;
            SysPar.srs{3}.combOffset = 2;
            SysPar.srs{4}.combOffset = 3;

            SysPar.srs{5}.combOffset = 0;
            SysPar.srs{6}.combOffset = 1;
            SysPar.srs{7}.combOffset = 2;
            SysPar.srs{8}.combOffset = 3;

            SysPar.srs{1}.cyclicShift = 0;
            SysPar.srs{2}.cyclicShift = 3;
            SysPar.srs{3}.cyclicShift = 6;
            SysPar.srs{4}.cyclicShift = 9;

            SysPar.srs{5}.cyclicShift = 0;
            SysPar.srs{6}.cyclicShift = 3;
            SysPar.srs{7}.cyclicShift = 6;
            SysPar.srs{8}.cyclicShift = 9;

        elseif caseNum == 8421
            SysPar.testAlloc.srs = 8;
            SysPar.SimCtrl.N_UE  = 8;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});

            SysPar.srs{1}.usage = USAGE_BEAM_MGMT;
            SysPar.srs{2}.usage = USAGE_CODEBOOK;
            SysPar.srs{3}.usage = USAGE_NON_CODEBOOK;
            SysPar.srs{4}.usage = USAGE_BEAM_MGMT;

            SysPar.srs{5}.usage = USAGE_CODEBOOK;
            SysPar.srs{6}.usage = USAGE_NON_CODEBOOK;
            SysPar.srs{7}.usage = USAGE_BEAM_MGMT;
            SysPar.srs{8}.usage = USAGE_CODEBOOK;

            SysPar.srs{1}.timeStartPosition = 9;
            SysPar.srs{2}.timeStartPosition = 9;
            SysPar.srs{3}.timeStartPosition = 10;
            SysPar.srs{4}.timeStartPosition = 10;

            SysPar.srs{5}.timeStartPosition = 11;
            SysPar.srs{6}.timeStartPosition = 11;
            SysPar.srs{7}.timeStartPosition = 12;
            SysPar.srs{8}.timeStartPosition = 12;

            SysPar.srs{1}.combOffset = 0;
            SysPar.srs{2}.combOffset = 1;
            SysPar.srs{3}.combOffset = 2;
            SysPar.srs{4}.combOffset = 3;

            SysPar.srs{5}.combOffset = 0;
            SysPar.srs{6}.combOffset = 1;
            SysPar.srs{7}.combOffset = 2;
            SysPar.srs{8}.combOffset = 3;

        elseif ismember(caseNum, [8046,8512,8536,8538,8555])
            SysPar.testAlloc.srs = 16;
            SysPar.SimCtrl.N_UE  = 16;

            if caseNum == 8046
                SysPar.srs{1}.prgSize = 16;
            end
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});
            
            SysPar.srs{1}.timeStartPosition = 9;
            SysPar.srs{2}.timeStartPosition = 9;
            SysPar.srs{3}.timeStartPosition = 9;
            SysPar.srs{4}.timeStartPosition = 9;
            
            SysPar.srs{5}.timeStartPosition = 10;
            SysPar.srs{6}.timeStartPosition = 10;
            SysPar.srs{7}.timeStartPosition = 10;
            SysPar.srs{8}.timeStartPosition = 10;
            
            SysPar.srs{9}.timeStartPosition = 11;
            SysPar.srs{10}.timeStartPosition = 11;
            SysPar.srs{11}.timeStartPosition = 11;
            SysPar.srs{12}.timeStartPosition = 11;
            
            SysPar.srs{13}.timeStartPosition = 12;
            SysPar.srs{14}.timeStartPosition = 12;
            SysPar.srs{15}.timeStartPosition = 12;
            SysPar.srs{16}.timeStartPosition = 12;
            
            SysPar.srs{1}.combOffset = 0;
            SysPar.srs{2}.combOffset = 1;
            SysPar.srs{3}.combOffset = 2;
            SysPar.srs{4}.combOffset = 3;
            
            SysPar.srs{5}.combOffset = 0;
            SysPar.srs{6}.combOffset = 1;
            SysPar.srs{7}.combOffset = 2;
            SysPar.srs{8}.combOffset = 3;
            
            SysPar.srs{9}.combOffset  = 0;
            SysPar.srs{10}.combOffset = 1;
            SysPar.srs{11}.combOffset = 2;
            SysPar.srs{12}.combOffset = 3;

            SysPar.srs{13}.combOffset = 0;
            SysPar.srs{14}.combOffset = 1;
            SysPar.srs{15}.combOffset = 2;
            SysPar.srs{16}.combOffset = 3;

%             SysPar.srs{1}.frequencyShift = 0;
%             SysPar.srs{2}.frequencyShift = 16;
%             SysPar.srs{3}.frequencyShift = 32;
%             SysPar.srs{4}.frequencyShift = 48;
%             
%             SysPar.srs{5}.frequencyShift = 0;
%             SysPar.srs{6}.frequencyShift = 16;
%             SysPar.srs{7}.frequencyShift = 32;
%             SysPar.srs{8}.frequencyShift = 48;
%             
%             SysPar.srs{9}.frequencyShift  = 0;
%             SysPar.srs{10}.frequencyShift = 16;
%             SysPar.srs{11}.frequencyShift = 32;
%             SysPar.srs{12}.frequencyShift = 48;
% 
%             SysPar.srs{13}.frequencyShift = 0;
%             SysPar.srs{14}.frequencyShift = 16;
%             SysPar.srs{15}.frequencyShift = 32;
%             SysPar.srs{16}.frequencyShift = 48;
            
 
        elseif ismember(caseNum, [8101:8164])
            SysPar.SimCtrl.timeDomainSim = 1;
            SysPar.Chan{1}.delay = mod(caseNum - 8101, 10)*1e-7; % sweep delay [0:0.1:1.0] us
            SysPar.Chan{1}.SNR = mod(caseNum - 8101, 30); % sweep SNR [0:1:30] dB
            SysPar.Chan{1}.CFO = 300; % add CFO
            % SysPar.Chan{1}.type = 'TDLA30-10-Low';
        elseif caseNum == 8201
            SysPar.carrier.N_grid_size_mu = 11; % 5 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8202
            SysPar.carrier.N_grid_size_mu = 24; % 10 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8203
            SysPar.carrier.N_grid_size_mu = 38; % 15 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8204
            SysPar.carrier.N_grid_size_mu = 51; % 20 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8205
            SysPar.carrier.N_grid_size_mu = 65; % 25 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8206
            SysPar.carrier.N_grid_size_mu = 78; % 30 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8207
            SysPar.carrier.N_grid_size_mu = 106; % 40 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8208
            SysPar.carrier.N_grid_size_mu = 133; % 50 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8209
            SysPar.carrier.N_grid_size_mu = 162; % 60 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8210
            SysPar.carrier.N_grid_size_mu = 189; % 70 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8211
            SysPar.carrier.N_grid_size_mu = 217; % 80 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8212
            SysPar.carrier.N_grid_size_mu = 245; % 90 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8213
            SysPar.carrier.N_grid_size_mu = 273; % 100 MHz 
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8214
            SysPar.carrier.mu = 0;
            SysPar.carrier.N_grid_size_mu = 25; % 5 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8215
            SysPar.carrier.mu = 0;
            SysPar.carrier.N_grid_size_mu = 52; % 10 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8216
            SysPar.carrier.mu = 0;
            SysPar.carrier.N_grid_size_mu = 79; % 15 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8217
            SysPar.carrier.mu = 0;
            SysPar.carrier.N_grid_size_mu = 106; % 20 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8218
            SysPar.carrier.mu = 0;
            SysPar.carrier.N_grid_size_mu = 133; % 25 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8219
            SysPar.carrier.mu = 0;
            SysPar.carrier.N_grid_size_mu = 160; % 30 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8220
            SysPar.carrier.mu = 0;
            SysPar.carrier.N_grid_size_mu = 216; % 40 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8221
            SysPar.carrier.mu = 0;
            SysPar.carrier.N_grid_size_mu = 270; % 50 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        elseif caseNum == 8222
            SysPar.Chan{1}.gain = sqrt(10);
        elseif caseNum == 8223
            SysPar.Chan{1}.gain = sqrt(0.1);
        elseif caseNum == 8224
            SysPar.Chan{1}.SNR = 0;
            SysPar.Chan{1}.gain = 100;
            SysPar.SimCtrl.alg.srs_chEst_toL2_constant_scaler = 32;
        elseif caseNum == 8225
            SysPar.Chan{1}.SNR = 40;
            SysPar.Chan{1}.gain = 0.01;
        elseif caseNum == 8226
            SysPar.SimCtrl.forceRxZero = 1;
        elseif caseNum == 8227
            SysPar.carrier.N_grid_size_mu = 100; % 40 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;   
        elseif ismember(caseNum, [8801, 8802, 8803, 8804])
            rng(1);
            
            % if ismember(caseNum, [8801, 8802])
            %     SysPar.carrier.Nant_gNB        = 32;
            %     SysPar.carrier.Nant_gNB_srs    = 32;
            %     SysPar.carrier.N_FhPort_DL     = 8;
            %     SysPar.carrier.N_FhPort_UL     = 4;
            %     SysPar.SimCtrl.enable_dynamic_BF = 1;
            % elseif ismember(caseNum, [8803, 8804])
            %     SysPar.carrier.Nant_gNB        = 64;
            %     SysPar.carrier.Nant_gNB_srs    = 64;
            %     SysPar.carrier.N_FhPort_DL     = 8;
            %     SysPar.carrier.N_FhPort_UL     = 4;
            % end

    

            SysPar.Chan{1}.SNR = 0;
            SysPar.testAlloc.srs = 8;
            SysPar.SimCtrl.N_UE = 8;
            [SysPar.srs{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.srs{1});
            [SysPar.Chan{2:SysPar.SimCtrl.N_UE}] = deal(SysPar.Chan{1});

            SysPar.srs{1}.combOffset = 0;
            SysPar.srs{2}.combOffset = 1;
            SysPar.srs{3}.combOffset = 2;
            SysPar.srs{4}.combOffset = 3;
            SysPar.srs{5}.combOffset = 0;
            SysPar.srs{6}.combOffset = 1;
            SysPar.srs{7}.combOffset = 2;
            SysPar.srs{8}.combOffset = 3;

            SysPar.srs{1}.cyclicShift = 0;
            SysPar.srs{2}.cyclicShift = 0;
            SysPar.srs{3}.cyclicShift = 0;
            SysPar.srs{4}.cyclicShift = 0;
            SysPar.srs{5}.cyclicShift = 1;
            SysPar.srs{6}.cyclicShift = 1;
            SysPar.srs{7}.cyclicShift = 1;
            SysPar.srs{8}.cyclicShift = 1;
        elseif caseNum == 8416 || caseNum == 8417
            SysPar.carrier.N_grid_size_mu = 78; % 30 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;        
        elseif caseNum == 8418 ||caseNum == 8419
            SysPar.carrier.N_grid_size_mu = 133; % 50 MHz
            SysPar.srs{1}.BWPSize = SysPar.carrier.N_grid_size_mu;
        end
                
        if ismember(caseNum, [8412 8416 8418 8514 8516 8518 8520 8522 8524 8540 8542:2:8554])
            SysPar.srs{1}.RNTI = 1;
            SysPar.srs{2}.RNTI = 4;
            SysPar.srs{3}.RNTI = 6;
            SysPar.srs{4}.RNTI = 7;
            SysPar.srs{5}.RNTI = 8;
            SysPar.srs{6}.RNTI = 9;
            SysPar.srs{7}.RNTI = 10;
            SysPar.srs{8}.RNTI = 3;
        end

        if caseNum == 8413 || caseNum == 8417 || caseNum == 8419
            SysPar.srs{1}.RNTI = 1;
            SysPar.srs{2}.RNTI = 4;
            SysPar.srs{3}.RNTI = 6;
            SysPar.srs{4}.RNTI = 10;
            SysPar.srs{5}.RNTI = 11;
            SysPar.srs{6}.RNTI = 12;
            SysPar.srs{7}.RNTI = 13;
            SysPar.srs{8}.RNTI = 14;
        end
        
        if caseNum == 8541
            SysPar.srs{1}.RNTI = 1;
            SysPar.srs{2}.RNTI = 4;
            SysPar.srs{3}.RNTI = 6;
            SysPar.srs{4}.RNTI = 7;
        end
        if caseNum == 8543
            SysPar.srs{1}.RNTI = 1;
            SysPar.srs{2}.RNTI = 6;
            SysPar.srs{4}.RNTI = 7;
        end
        if caseNum == 8545
            SysPar.srs{1}.RNTI = 1;
            SysPar.srs{2}.RNTI = 4;
            SysPar.srs{3}.RNTI = 6;
            SysPar.srs{4}.RNTI = 9;
            SysPar.srs{5}.RNTI = 10;
            SysPar.srs{6}.RNTI = 3;
        end
        if caseNum == 8547
            SysPar.srs{1}.RNTI = 1;
            SysPar.srs{2}.RNTI = 4;
            SysPar.srs{3}.RNTI = 6;
            SysPar.srs{4}.RNTI = 10;
            SysPar.srs{5}.RNTI = 3;
        end
        if caseNum == 8549
            SysPar.srs{1}.RNTI = 4;
            SysPar.srs{2}.RNTI = 9;
            SysPar.srs{3}.RNTI = 10;
            SysPar.srs{4}.RNTI = 3;
        end
        if caseNum == 8551
            SysPar.srs{1}.RNTI = 7;
            SysPar.srs{2}.RNTI = 6;
            SysPar.srs{3}.RNTI = 1;
            SysPar.srs{4}.RNTI = 8;
        end
        if caseNum == 8553
            SysPar.srs{1}.RNTI = 7;
            SysPar.srs{2}.RNTI = 1;
            SysPar.srs{3}.RNTI = 6;
            SysPar.srs{4}.RNTI = 8;
            SysPar.srs{5}.RNTI = 4;
            SysPar.srs{6}.RNTI = 5;
            SysPar.srs{7}.RNTI = 2;
            SysPar.srs{8}.RNTI = 9;
            SysPar.srs{9}.RNTI = 12;
            SysPar.srs{10}.RNTI = 11;
            SysPar.srs{11}.RNTI = 10;
            SysPar.srs{12}.RNTI = 3;
        end

        if ismember(caseNum, [8401:8421])
            SysPar.carrier.Nant_gNB        = 32;
            SysPar.carrier.Nant_gNB_srs    = 32;
            SysPar.carrier.N_FhPort_DL     = 8;
            SysPar.carrier.N_FhPort_UL     = 4;
            SysPar.SimCtrl.enable_dynamic_BF = 1;
        end
        if ismember(caseNum, [8046,8501:8599])
            SysPar.carrier.Nant_gNB        = 64;
            SysPar.carrier.Nant_gNB_srs    = 64;
            SysPar.carrier.N_FhPort_DL     = 16;
            SysPar.carrier.N_FhPort_UL     = 16;
            SysPar.SimCtrl.enable_dynamic_BF = 1;
        end
        if ismember(caseNum, [8046,8512,8536,8538,8555])
            SysPar.srs{1}.RNTI = 4;
            SysPar.srs{2}.RNTI = 13;
            SysPar.srs{3}.RNTI = 6;
            SysPar.srs{4}.RNTI = 11;
            SysPar.srs{5}.RNTI = 8;
            SysPar.srs{6}.RNTI = 3;
            SysPar.srs{7}.RNTI = 16;
            SysPar.srs{8}.RNTI = 14;
            SysPar.srs{9}.RNTI = 5;
            SysPar.srs{10}.RNTI = 15;
            SysPar.srs{11}.RNTI = 9;
            SysPar.srs{12}.RNTI = 7;
            SysPar.srs{13}.RNTI = 10;
            SysPar.srs{14}.RNTI = 2;
            SysPar.srs{15}.RNTI = 12;
            SysPar.srs{16}.RNTI = 1;
        end
        if ismember(caseNum, 8559:8566)
            SysPar.SimCtrl.alg.srs_chEst_alg_selector = 1;
            SysPar.Chan{1}.SNR = 0;
            SysPar.SimCtrl.timeDomainSim = 1;
            SysPar.SimCtrl.enable_dynamic_BF = 0;
            SysPar.Chan{1}.model_source='MATLAB5Gtoolbox';
            SysPar.Chan{1}.type='CDL';
            SysPar.Chan{1}.DelayProfile='CDL-B';
            SysPar.Chan{1}.DelaySpread=1e-7;
            SysPar.Chan{1}.UE_AntArraySize = [1 2 2];
            SysPar.carrier.Nant_UE = prod(SysPar.Chan{1}.UE_AntArraySize);
            SysPar.Chan{1}.UE_AntPattern = 'isotropic';
            SysPar.Chan{1}.UE_AntPolarizationAngles = [0 90];
            SysPar.Chan{1}.gNB_AntArraySize = [4 8 2];
            SysPar.Chan{1}.gNB_AntPattern = 'isotropic';
            SysPar.Chan{1}.gNB_AntPolarizationAngles = [0 90];
        end
        if ismember(caseNum, 8562:8564)
            SysPar.srs{1}.prgSize = 1;
        end
        if ismember(caseNum, 8565)
            SysPar.Chan{1}.SNR = -30;
        end
        if ismember(caseNum, 8566)
            SysPar.Chan{1}.SNR = 30;
        end
        if caseNum == 8058
            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 4;
        end

        if caseNum == 8059
            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 2;
        end

        if caseNum == 8060
            SysPar.testAlloc.srs = 3;
            SysPar.SimCtrl.N_UE  = 3;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 2;
            SysPar.srs{2}.numAntPorts = 2;

            SysPar.srs{3}             = SysPar.srs{1};
            SysPar.srs{3}.cyclicShift = 4;
        end

        if caseNum == 8061
            SysPar.testAlloc.srs = 4;
            SysPar.SimCtrl.N_UE  = 4;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 2;

            SysPar.srs{3}             = SysPar.srs{1};
            SysPar.srs{3}.cyclicShift = 4;

            SysPar.srs{4}             = SysPar.srs{1};
            SysPar.srs{4}.cyclicShift = 6;
        end

        if caseNum == 8062
            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 1;
        end

        if caseNum == 8063
            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 6;
        end

        if caseNum == 8064
            SysPar.testAlloc.srs = 3;
            SysPar.SimCtrl.N_UE  = 3;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 2;

            SysPar.srs{3}             = SysPar.srs{1};
            SysPar.srs{3}.cyclicShift = 4;
        end

        if caseNum == 8065
            SysPar.testAlloc.srs = 3;
            SysPar.SimCtrl.N_UE  = 3;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 1;

            SysPar.srs{3}             = SysPar.srs{1};
            SysPar.srs{3}.cyclicShift = 2;
        end
        if caseNum == 8066
            SysPar.testAlloc.srs = 4;
            SysPar.SimCtrl.N_UE  = 4;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 3;

            SysPar.srs{3}             = SysPar.srs{1};
            SysPar.srs{3}.cyclicShift = 6;

            SysPar.srs{4}             = SysPar.srs{1};
            SysPar.srs{4}.cyclicShift = 9;
        end

        if caseNum == 8067
            SysPar.testAlloc.srs = 3;
            SysPar.SimCtrl.N_UE  = 3;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 3;
            SysPar.srs{2}.numAntPorts = 1;

            SysPar.srs{3}             = SysPar.srs{1};
            SysPar.srs{3}.cyclicShift = 9;
            SysPar.srs{3}.numAntPorts = 1;
        end

        if caseNum == 8068
            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 6;
            SysPar.srs{2}.numAntPorts = 1;
        end

        if caseNum == 8069
            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 3;
            SysPar.srs{2}.numAntPorts = 1;
        end

        if caseNum == 8070
            SysPar.testAlloc.srs = 5;
            SysPar.SimCtrl.N_UE  = 5;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 2;
            SysPar.srs{2}.numAntPorts = 1;

            SysPar.srs{3}             = SysPar.srs{1};
            SysPar.srs{3}.cyclicShift = 4;
            SysPar.srs{3}.numAntPorts = 1;

            SysPar.srs{4}             = SysPar.srs{1};
            SysPar.srs{4}.cyclicShift = 6;
            SysPar.srs{4}.numAntPorts = 1;

            SysPar.srs{5}             = SysPar.srs{1};
            SysPar.srs{5}.cyclicShift = 8;
            SysPar.srs{5}.numAntPorts = 1;
        end

        if caseNum == 8071
            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 6;
            SysPar.srs{2}.numAntPorts = 1;
        end

        if caseNum == 8072
            SysPar.carrier.Nant_gNB          = 64;
            SysPar.carrier.Nant_gNB_srs      = 64;
            SysPar.carrier.N_FhPort_DL       = 16;
            SysPar.carrier.N_FhPort_UL       = 16;
            SysPar.SimCtrl.enable_dynamic_BF = 1;

            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 6;
            SysPar.srs{2}.numAntPorts = 1;
        end

        if caseNum == 8073
            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 2;
        end

        if caseNum == 8074
            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 2;
        end

        if caseNum == 8075
            SysPar.testAlloc.srs = 12;
            SysPar.SimCtrl.N_UE  = 12;

            for i=1:11
                SysPar.srs{i+1} = SysPar.srs{1};
                SysPar.srs{i+1}.cyclicShift = i;
            end
        end

        if caseNum == 8076
            SysPar.testAlloc.srs = 10;
            SysPar.SimCtrl.N_UE  = 10;

            for i=1:10
                SysPar.srs{i+1} = SysPar.srs{1};
                SysPar.srs{i+1}.cyclicShift = i;
            end
        end

        if caseNum == 8077
            SysPar.SimCtrl.timeDomainSim = 1;

            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 4;

            SysPar.Chan{1}.delay = 0.2 * 10^(-6);
            SysPar.Chan{2}       = SysPar.Chan{1};
            SysPar.Chan{2}.delay = 0.4 * 10^(-6);
        end

        if caseNum == 8078
            SysPar.SimCtrl.timeDomainSim = 1;

            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 4;

            SysPar.Chan{1}.delay = 0.2 * 10^(-6);
            SysPar.Chan{2}       = SysPar.Chan{1};
            SysPar.Chan{2}.delay = 0.4 * 10^(-6);
        end

        if caseNum == 8079
            SysPar.SimCtrl.timeDomainSim = 1;

            SysPar.testAlloc.srs = 4;
            SysPar.SimCtrl.N_UE  = 4;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 2;

            SysPar.srs{3}             = SysPar.srs{1};
            SysPar.srs{3}.cyclicShift = 4;

            SysPar.srs{4}             = SysPar.srs{1};
            SysPar.srs{4}.cyclicShift = 6;

            SysPar.Chan{1}.delay = 0.2 * 10^(-6);

            SysPar.Chan{2}       = SysPar.Chan{1};
            SysPar.Chan{2}.delay = 0.4 * 10^(-6);

            SysPar.Chan{3}       = SysPar.Chan{1};
            SysPar.Chan{3}.delay = 0.2 * 10^(-6);

            SysPar.Chan{4}       = SysPar.Chan{1};
            SysPar.Chan{4}.delay = 0.1 * 10^(-6);
        end

        if caseNum == 8080
            SysPar.SimCtrl.timeDomainSim = 1;

            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 6;

            SysPar.Chan{1}.delay = 0.2 * 10^(-6);
            SysPar.Chan{2}       = SysPar.Chan{1};
            SysPar.Chan{2}.delay = 0.4 * 10^(-6);
        end

        if caseNum == 8081
            SysPar.SimCtrl.timeDomainSim = 1;
            
            SysPar.testAlloc.srs = 4;
            SysPar.SimCtrl.N_UE  = 4;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 3;

            SysPar.srs{3}             = SysPar.srs{1};
            SysPar.srs{3}.cyclicShift = 6;

            SysPar.srs{4}             = SysPar.srs{1};
            SysPar.srs{4}.cyclicShift = 9;

            SysPar.Chan{1}.delay = 0.1 * 10^(-6);

            SysPar.Chan{2}       = SysPar.Chan{1};
            SysPar.Chan{2}.delay = 0.3 * 10^(-6);

            SysPar.Chan{3}       = SysPar.Chan{1};
            SysPar.Chan{3}.delay = 0.2 * 10^(-6);

            SysPar.Chan{4}       = SysPar.Chan{1};
            SysPar.Chan{4}.delay = 0.1 * 10^(-6);
        end

        if caseNum == 8082
            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 4;

            SysPar.Chan{2}      = SysPar.Chan{1};
            SysPar.Chan{2}.gain = sqrt(0.1);
        end

        if caseNum == 8083
            SysPar.testAlloc.srs = 4;
            SysPar.SimCtrl.N_UE  = 4;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 2;

            SysPar.srs{3}             = SysPar.srs{1};
            SysPar.srs{3}.cyclicShift = 4;

            SysPar.srs{4}             = SysPar.srs{1};
            SysPar.srs{4}.cyclicShift = 6;

            SysPar.Chan{2}       = SysPar.Chan{1};
            SysPar.Chan{2}.gain  = sqrt(10^(5/10));

            SysPar.Chan{3}       = SysPar.Chan{1};
            SysPar.Chan{3}.gain  = sqrt(10^(-5/10));

            SysPar.Chan{4}       = SysPar.Chan{1};
            SysPar.Chan{4}.gain  = sqrt(10^(-10/10));
        end

        if caseNum == 8084
            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 6;

            SysPar.Chan{2}      = SysPar.Chan{1};
            SysPar.Chan{2}.gain = sqrt(0.1);
        end

        if caseNum == 8085
            SysPar.testAlloc.srs = 4;
            SysPar.SimCtrl.N_UE  = 4;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 3;

            SysPar.srs{3}             = SysPar.srs{1};
            SysPar.srs{3}.cyclicShift = 6;

            SysPar.srs{4}             = SysPar.srs{1};
            SysPar.srs{4}.cyclicShift = 9;

            SysPar.Chan{2}       = SysPar.Chan{1};
            SysPar.Chan{2}.gain  = sqrt(10^(5/10));

            SysPar.Chan{3}       = SysPar.Chan{1};
            SysPar.Chan{3}.gain  = sqrt(10^(-5/10));

            SysPar.Chan{4}       = SysPar.Chan{1};
            SysPar.Chan{4}.gain  = sqrt(10^(-10/10));
        end

        if caseNum == 8086
            SysPar.SimCtrl.timeDomainSim = 1;

            SysPar.testAlloc.srs = 2;
            SysPar.SimCtrl.N_UE  = 2;

            SysPar.srs{2}             = SysPar.srs{1};
            SysPar.srs{2}.cyclicShift = 4;

            SysPar.Chan{2}       = SysPar.Chan{1};
            SysPar.Chan{2}.gain  = sqrt(0.1);
            SysPar.Chan{2}.delay = 0.2 * 10^(-6); 
        end

        if caseNum == 8087
            SysPar.testAlloc.srs = 8;
            SysPar.SimCtrl.N_UE  = 8;

            SysPar.carrier.Nant_gNB        = 64;
            SysPar.carrier.Nant_gNB_srs    = 64;
            SysPar.carrier.N_FhPort_DL     = 16;
            SysPar.carrier.N_FhPort_UL     = 16;
            SysPar.SimCtrl.enable_dynamic_BF = 1;

            for i=1:8
                SysPar.srs{i+1} = SysPar.srs{1};
                SysPar.srs{i+1}.cyclicShift = i;
            end
        end

        if caseNum == 8088
            SysPar.testAlloc.srs = 12;
            SysPar.SimCtrl.N_UE  = 12;

            SysPar.carrier.Nant_gNB        = 64;
            SysPar.carrier.Nant_gNB_srs    = 64;
            SysPar.carrier.N_FhPort_DL     = 16;
            SysPar.carrier.N_FhPort_UL     = 16;
            SysPar.SimCtrl.enable_dynamic_BF = 1;

            for i=1:12
                SysPar.srs{i+1} = SysPar.srs{1};
                SysPar.srs{i+1}.cyclicShift = i;
            end
        end


        for idxUe = 1:length(SysPar.srs)
            digBFInterfaces                   = SysPar.carrier.Nant_gNB;
            SysPar.srs{idxUe}.idxUE           = idxUe-1;
            SysPar.srs{idxUe}.digBFInterfaces = digBFInterfaces;
            SysPar.srs{idxUe}.beamIdx         = [1:digBFInterfaces];
            if(SysPar.srs{idxUe}.RNTI == SysPar.srs{1}.RNTI)
                SysPar.srs{idxUe}.RNTI = SysPar.srs{1}.RNTI + idxUe - 1;
            end
            SysPar.srs{idxUe}.srsChestBufferIndex = SysPar.srs{idxUe}.RNTI - 1;
        end
        
        % update Nre_max which is used to calculate beta value in BFP
        SysPar.SimCtrl.oranComp.Nre_max = SysPar.carrier.N_grid_size_mu*12;
        
        % save SysPar into Cfg_<TC#>.yaml config file
        if SysPar.SimCtrl.genTV.genYamlCfg
            fileName = sprintf('Cfg_%04d.yaml', caseNum);
            WriteYaml(fileName, SysPar);
        end
        
%         if SysPar.SimCtrl.genTV.enable && SysPar.SimCtrl.genTV.launchPattern
%             if ~ismember(caseNum, disabled_TC)
%                 LPFileName = 'launch_pattern_nrSim';
%             else
%                 LPFileName = 'disabled_launch_pattern_nrSim';
%             end
%             slotIdx =  SysPar.SimCtrl.genTV.slotIdx;
%             genSingleSlotLPFile(LPFileName, caseNum, slotIdx);
%         end
        
        [SysPar, UE, gNB] = nrSimulator(SysPar);        
        SimCtrl = SysPar.SimCtrl;        

	% Collect all results and use worst case for detection
	nSrs = length(SimCtrl.results.srs);
	snrErrs = zeros([1 nSrs]);
	toErrs = zeros([1 nSrs]);
    hestErrs = zeros([1 nSrs]);
	for k=1:nSrs % check all PDUs. Code multiplexing TCs 8411, 8801 & 8802 currently fail
        totalCnt = SimCtrl.results.srs{k}.totalCnt;
		snrErrs(k) = sqrt(SimCtrl.results.srs{k}.snrErr/totalCnt);
		toErrs(k)  = sqrt(SimCtrl.results.srs{k}.toErr/totalCnt);
        hestErrs(k) = 10*log10(SimCtrl.results.srs{k}.hestErr/totalCnt);
	end

        snrErr = max(snrErrs);
        toErr  = max(toErrs);
        hestErr  = max(hestErrs);
        
        % if snrErr > 3 || toErr > 0.3
        if toErr > 0.3
            Detected = 0;
        else
            Detected = 1;
        end
        
        % bypass detection check for forceRxZero case
        if ismember(caseNum, [8226])
            Detected = 1;
        end
        
        % bypass detection check for unsupported code multiplexing cases, detection fail
        if ismember(caseNum, [8801 8802 8411 8415])
            Detected = 1;
        end

        if ~Detected
            detErr = detErr + 1;
        end

        testPass = 1;
        if testCompliance
            nComp = nComp + 1;
            for idxUe = 1:SysPar.SimCtrl.N_UE
                srs     = UE{idxUe}.Mac.Config.srs{1};
                nAP     = srs.numAntPorts;
                carrier = UE{idxUe}.Mac.Config.carrier;
                Xtf_nr  = UE{idxUe}.Phy.tx.Xtf(:,:,1:nAP);
                Xtf_5g  = hSRSGen(srs, carrier);
                
                err_Xtf = sum(sum(sum(abs(Xtf_nr - Xtf_5g))));
                if (err_Xtf > 1e-4)
                    testPass = 0;
                end
            end
            if ~testPass
                errCnt = errCnt + 1;
            end
        end
        fprintf('%4d %4d  %2d   %2d  %4d  %4d  %4d  %4d  %4d  %4d  %4d    %4d %4d  %4d  %4d  %4d  %4d  %4d    %4d   %4d  %4d %4d  %4.1f   %4.1f   %5.2f    %5.2f\n',...
            CFG{idxSet, 1}, CFG{idxSet, 2}, CFG{idxSet, 3}, CFG{idxSet, 4}, ...
            CFG{idxSet, 5}, CFG{idxSet, 6}, CFG{idxSet, 7}, CFG{idxSet, 8}, ...
            CFG{idxSet, 9},  CFG{idxSet, 10},  CFG{idxSet, 11},  CFG{idxSet, 12}, ...
            CFG{idxSet, 13}, CFG{idxSet, 14}, CFG{idxSet, 15}, CFG{idxSet, 16}, ...
            CFG{idxSet, 17}, CFG{idxSet, 18}, CFG{idxSet, 19}, CFG{idxSet, 20}, ...            
            testPass, Detected, SysPar.Chan{1}.SNR, snrErr, toErr, hestErr);
    end
end

fprintf('------------------------------------------------------------------------------------------------------------------------------------------------------------------\n');
fprintf('Total Compliance TC = %d, PASS = %d, FAIL = %d, Total TV generated = %d\n\n', nComp, nComp-errCnt, errCnt, nTV);
toc; 
fprintf('\n');
