% SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
% SPDX-License-Identifier: Apache-2.0
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
% http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.

% This function is used to compile runSim with mcc

build_output_folder = 'bin/';
if ~exist(build_output_folder, 'dir')
    mkdir(build_output_folder)
end
% IMPORTANT: please DONOT include the file 'nr_matlab/cfg_template.yaml' in
% the following -I, otherwise ReadYaml() will load it instead of loading
% the expanded one from batchsim launch
mcc -d 'bin/' ...
    -I 'bfw/' ...
    -I 'cfg/' ...
    -I 'config/' -a 'config/initSionnaChan.m'...
    -I 'channel/' ...    
    -I 'csirs/' ...
    -I 'fhComp/' ...
    -I 'pdcch/' ...
    -I 'prach/' ...
    -I 'pucch/' ...
    -I 'pxsch/' -a 'pxsch/*.csv'...
    -I 'standalone/' ...
    -I 'refGen/' ...
    -I 'scripts/' ...
    -I 'shared/' ...
    -I 'srs/' ...
    -I 'ssb/' ...
    -I 'rf/' ...
    -I 'util/' ...
    -I 'test/' ...
    -I 'Varray/' ...
    -I 'yamlmatlab/' ...
    -I 'yamlmatlab/external/' -a 'yamlmatlab/external/*.*'...
    -I 'yamlmatlab/extras/' ...
    -m -v -R '-nodisplay' runSim.m
  
