% SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
% SPDX-License-Identifier: Apache-2.0
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
% http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.

function table = derive_chest_mmse_coeff(mu, delay_mean, win_size)
    global SimCtrl;
    if nargin < 3
        win_size = SimCtrl.delaySpread;
    end
    % derive filter coeff
    table.W_lower  = derive_legacy_lower(10^(-3),15e3*2^(mu),win_size);
    table.W_middle = derive_legacy_middle(10^(-3),15e3*2^(mu),win_size);
    table.W_upper  = derive_legacy_upper(10^(-3),15e3*2^(mu),win_size);
    
    table.W4_upper  = derive_upper_filter(10^(-3),15e3*2^(mu),win_size);
    table.W4_middle = derive_middle_filter(10^(-3),15e3*2^(mu),win_size);
    table.W4_lower  = derive_lower_filter(10^(-3),15e3*2^(mu),win_size);

    % use W with vPRBs
%     table.W4_upper  = derive_upper_filter_with_vPRB(10^(-3),15e3*2^(mu),win_size);
%     table.W4_lower  = derive_lower_filter_with_vPRB(10^(-3),15e3*2^(mu),win_size);
    
    table.W3 = derive_small_filter(3,10^(-3),15e3*2^(mu),win_size);
    table.W2 = derive_small_filter(2,10^(-3),15e3*2^(mu),win_size);
    table.W1 = derive_small_filter(1,10^(-3),15e3*2^(mu),win_size);

    % derive shift seq
    df     = 15e3*2^(mu);
    f_dmrs = 0 : 2 : (8*12 - 1);
    f_dmrs = df * f_dmrs';    
    f_data = -1 : (8*12 - 1);
    f_data = df * f_data';
    global SimCtrl;
    shiftSeq  = exp(2*pi*1i*delay_mean*f_dmrs);
    % When performing delay estimation in cuphy, the shift and unshift sequences will be
    % generated by cuphy in single precision. For the legacy channel estimation algorithm,
    % the shift and unshift sequence is read from the test vector and should be quantized
    % to fp16.
%    shiftSeq  = single(fp16nv(real(shiftSeq), SimCtrl.fp16AlgoSel)) + 1i*single(fp16nv(imag(shiftSeq), SimCtrl.fp16AlgoSel));
    shiftSeq  = single(shiftSeq);
    shiftSeq4 = shiftSeq(1 : 4*6);
    
    unShiftSeq  = exp(-2*pi*1i*delay_mean*f_data);
%    unShiftSeq  = single(fp16nv(real(unShiftSeq), SimCtrl.fp16AlgoSel)) + 1i*single(fp16nv(imag(unShiftSeq), SimCtrl.fp16AlgoSel));
    unShiftSeq  = single(unShiftSeq);
    unShiftSeq4 = unShiftSeq(1 : (12*4 + 1));
    
    table.shiftSeq    = shiftSeq;
    table.shiftSeq4   = shiftSeq4;
    table.unShiftSeq  = unShiftSeq;
    table.unShiftSeq4 = unShiftSeq4;
end