% SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
% SPDX-License-Identifier: Apache-2.0
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
% http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.

function DmrsSymbPos = findDmrsSymbPos(sym0, nSym, dmrs0, maxLen, addPos, dlul, mappingType)


DmrsSymbPos = zeros(1, 14);

if strcmp(mappingType, 'typeA')    
    
    ld = sym0 + nSym;    
    if addPos == 1 && dmrs0 == 3 & 0
        L1 = 12;
    else
        L1 = 11;
    end
    
    % TS38.211 7.4.1.1.2
    dlDmrsTable1 = { ...
        {}, {}, {}, {};...
        {}, {}, {}, {};...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0, 7}, {dmrs0, 7}, {dmrs0, 7};...
        {dmrs0}, {dmrs0, 7}, {dmrs0, 7}, {dmrs0, 7};...
        {dmrs0}, {dmrs0, 9}, {dmrs0, 6, 9}, {dmrs0, 6, 9};...
        {dmrs0}, {dmrs0, 9}, {dmrs0, 6, 9}, {dmrs0, 6, 9};...
        {dmrs0}, {dmrs0, 9}, {dmrs0, 6, 9}, {dmrs0, 5, 8, 11};...
        {dmrs0}, {dmrs0, L1}, {dmrs0, 7, L1}, {dmrs0, 5, 8, 11};...
        {dmrs0}, {dmrs0, L1}, {dmrs0, 7, L1}, {dmrs0, 5, 8, 11}...
        };
    
    dlDmrsTable2 = { ...
        {}, {};...
        {}, {};...
        {}, {};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0, 8};...
        {dmrs0}, {dmrs0, 8};...
        {dmrs0}, {dmrs0, 8};...
        {dmrs0}, {dmrs0, 10};...
        {dmrs0}, {dmrs0, 10}...
        };
    
    % TS38.211 6.4.1.1.3
    ulDmrsTable1 = { ...
        {}, {}, {}, {};...
        {}, {}, {}, {};...
        {}, {}, {}, {};...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0, 7}, {dmrs0, 7}, {dmrs0, 7};...
        {dmrs0}, {dmrs0, 7}, {dmrs0, 7}, {dmrs0, 7};...
        {dmrs0}, {dmrs0, 9}, {dmrs0, 6, 9}, {dmrs0, 6, 9};...
        {dmrs0}, {dmrs0, 9}, {dmrs0, 6, 9}, {dmrs0, 6, 9};...
        {dmrs0}, {dmrs0, 9}, {dmrs0, 6, 9}, {dmrs0, 5, 8, 11};...
        {dmrs0}, {dmrs0, 11}, {dmrs0, 7, 11}, {dmrs0, 5, 8, 11};...
        {dmrs0}, {dmrs0, 11}, {dmrs0, 7, 11}, {dmrs0, 5, 8, 11}...
        };
    
    ulDmrsTable2 = { ...
        {}, {};...
        {}, {};...
        {}, {};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0, 8};...
        {dmrs0}, {dmrs0, 8};...
        {dmrs0}, {dmrs0, 8};...
        {dmrs0}, {dmrs0, 10};...
        {dmrs0}, {dmrs0, 10}...
        };
    
else % mapping type B
    
    dmrs0 = sym0;
    ld = nSym;
    
    % TS38.211 7.4.1.1.2
    dlDmrsTable1 = { ...
        {}, {}, {}, {};...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...% ld=2
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...% ld=4
        {dmrs0}, {dmrs0, dmrs0+4}, {dmrs0, dmrs0+4}, {dmrs0, dmrs0+4};...
        {dmrs0}, {dmrs0, dmrs0+4}, {dmrs0, dmrs0+4}, {dmrs0, dmrs0+4};... % ld=6
        {dmrs0}, {dmrs0, dmrs0+4}, {dmrs0, dmrs0+4}, {dmrs0, dmrs0+4};...
        {dmrs0}, {dmrs0, dmrs0+6}, {dmrs0, dmrs0+3, dmrs0+6}, {dmrs0, dmrs0+3, dmrs0+6};... % ld=8
        {dmrs0}, {dmrs0, dmrs0+7}, {dmrs0, dmrs0+4, dmrs0+7}, {dmrs0, dmrs0+4, dmrs0+7};...
        {dmrs0}, {dmrs0, dmrs0+7}, {dmrs0, dmrs0+4, dmrs0+7}, {dmrs0, dmrs0+4, dmrs0+7};... % ld=10
        {dmrs0}, {dmrs0, dmrs0+8}, {dmrs0, dmrs0+4, dmrs0+8}, {dmrs0, dmrs0+3, dmrs0+6, dmrs0+9};...
        {dmrs0}, {dmrs0, dmrs0+9}, {dmrs0, dmrs0+5, dmrs0+9}, {dmrs0, dmrs0+3, dmrs0+6, dmrs0+9};... % ld=12
        {dmrs0}, {dmrs0, dmrs0+9}, {dmrs0, dmrs0+5, dmrs0+9}, {dmrs0, dmrs0+3, dmrs0+6, dmrs0+9};...
        {}, {}, {}, {};...
        };
    
    dlDmrsTable2 = { ...
        {}, {};...
        {}, {};...
        {}, {};...
        {}, {};...
        {dmrs0}, {dmrs0};... % ld=5
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0, dmrs0+5};... % ld=8
        {dmrs0}, {dmrs0, dmrs0+5};...
        {dmrs0}, {dmrs0, dmrs0+7};... % ld=10
        {dmrs0}, {dmrs0, dmrs0+7};...
        {dmrs0}, {dmrs0, dmrs0+8};... % ld=12
        {dmrs0}, {dmrs0, dmrs0+8};...
        {}, {};...
        };
    
    % TS38.211 6.4.1.1.3
    ulDmrsTable1 = { ...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0}, {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0, dmrs0+4}, {dmrs0, dmrs0+4}, {dmrs0, dmrs0+4};...
        {dmrs0}, {dmrs0, dmrs0+4}, {dmrs0, dmrs0+4}, {dmrs0, dmrs0+4};...
        {dmrs0}, {dmrs0, dmrs0+4}, {dmrs0, dmrs0+4}, {dmrs0, dmrs0+4};...
        {dmrs0}, {dmrs0, dmrs0+6}, {dmrs0, dmrs0+3, dmrs0+6}, {dmrs0, dmrs0+3, dmrs0+6};...
        {dmrs0}, {dmrs0, dmrs0+6}, {dmrs0, dmrs0+3, dmrs0+6}, {dmrs0, dmrs0+3, dmrs0+6};...
        {dmrs0}, {dmrs0, dmrs0+8}, {dmrs0, dmrs0+4, dmrs0+8}, {dmrs0, dmrs0+3, dmrs0+6, dmrs0+9};...
        {dmrs0}, {dmrs0, dmrs0+8}, {dmrs0, dmrs0+4, dmrs0+8}, {dmrs0, dmrs0+3, dmrs0+6, dmrs0+9};...        
        {dmrs0}, {dmrs0, dmrs0+10}, {dmrs0, dmrs0+5, dmrs0+10}, {dmrs0, dmrs0+3, dmrs0+6, dmrs0+9};...
        {dmrs0}, {dmrs0, dmrs0+10}, {dmrs0, dmrs0+5, dmrs0+10}, {dmrs0, dmrs0+3, dmrs0+6, dmrs0+9};...
        {dmrs0}, {dmrs0, dmrs0+10}, {dmrs0, dmrs0+5, dmrs0+10}, {dmrs0, dmrs0+3, dmrs0+6, dmrs0+9};...
        }; 
    
    ulDmrsTable2 = { ...
        {}, {};...
        {}, {};...
        {}, {};...
        {}, {};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0};...
        {dmrs0}, {dmrs0, dmrs0+5};...
        {dmrs0}, {dmrs0, dmrs0+5};...
        {dmrs0}, {dmrs0, dmrs0+7};...
        {dmrs0}, {dmrs0, dmrs0+7};...
        {dmrs0}, {dmrs0, dmrs0+9};...
        {dmrs0}, {dmrs0, dmrs0+9};...
        {dmrs0}, {dmrs0, dmrs0+9}...
        };    
end

if strcmp(dlul, 'DL')
    if maxLen == 1
        idx = cell2mat(dlDmrsTable1{ld, addPos+1});
        DmrsSymbPos(idx+1) = 1;
    else
        idx = cell2mat(dlDmrsTable2{ld, addPos+1});
        DmrsSymbPos(idx+1) = 1;
        DmrsSymbPos(idx+2) = 1;
    end
else
    if maxLen == 1
        idx = cell2mat(ulDmrsTable1{ld, addPos+1});
        DmrsSymbPos(idx+1) = 1;
    else
        idx = cell2mat(ulDmrsTable2{ld, addPos+1});
        DmrsSymbPos(idx+1) = 1;
        DmrsSymbPos(idx+2) = 1;
    end
end
        
return
    
                    
        
