# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Memory Performance Plotting Script

This script generates memory usage and frequency plots from GPU performance measurement data. The input json file can be generated by running the testbench using Python interface with --measure_power option.

Expected Input File Format:
- JSON files containing GPU performance data from nvidia-smi measurements
- Each file should have the following structure:
  {
    "testConfig": {
      ...,
      "sweeps": number_of_sweeps,
      ...,
      "gpuName": "GPU Model Name",
      ...,
    },
    "XX": [  // where XX is the cell count (e.g., "08+00", "12+00", etc.)
      [sm_clock, mem_clock, power_draw, mem_used, gpu_util, mem_util, temperature],
      [sm_clock, mem_clock, power_draw, mem_used, gpu_util, mem_util, temperature],
      ...
    ]
  }

Example JSON structure:
  {
    "testConfig": {
      ...,
      "sweeps": 8,
      ...,
      "gpuName": "NVIDIA GH200 480GB",
      ...,
    },
    "08+00": [
      [1980, 2619, 143.28, 8192, 95, 4, 31],
      [1875, 2619, 145.12, 8256, 92, 4, 32]
    ]
  }

Usage:
  python memory_plot.py --filenames file1.json --cells 8+0

Output:
- Generates memory.png with two subplots:
  1. CDF of memory frequency distribution
  2. Memory usage over time
"""

import json
import matplotlib.pyplot as plt
import argparse
import numpy as np
import os

base = argparse.ArgumentParser()
base.add_argument(
    "--filenames",
    type=str,
    nargs="+",
    dest="filenames",
    help="Specifies the files containing the results",
    required=True,
)
base.add_argument(
    "--cells",
    type=str,
    dest="cells",
    help="Specifies the number of cells to focus analysis on",
    required=True,
)
base.add_argument(
    "--short_legend",
    action="store_true",
    default=False,
    dest="is_short_legend",
    help="whether add platform and nSlots in each legend",
)
args = base.parse_args()

gpu_freq = []
mem_freq = []
mem_used = []
testConfig = []

if "+" in args.cells:
    cells = "+".join([str(x).zfill(2) for x in args.cells.split("+")])
else:
    cells = str(args.cells).zfill(2)

for filename in args.filenames:
    try:
        with open(filename, "r") as ifile:
            try:
                data = json.load(ifile)
            except json.JSONDecodeError as e:
                print(f"Error parsing JSON from {filename}: {e}")
                continue
            
            gpu_freq.extend([int(x[0]) for x in data[cells]])
            mem_freq.extend([int(x[1]) for x in data[cells]])
            mem_used.extend([float(x[3]) for x in data[cells]])
            
            # Add test config once per file, not for each data point
            testConfig.append(data['testConfig']['gpuName'] + ' ' + str(data['testConfig']['sweeps']) + ' slots')
            
    except IOError as e:
        print(f"Error opening file {filename}: {e}")
        continue

# Validate that we have data before computing statistics
if not mem_used:
    print("Warning: No memory usage data loaded. Skipping memory statistics.")
    max_mem_used = 0
else:
    max_mem_used = np.max(mem_used)

if not mem_freq:
    print("Warning: No memory frequency data loaded. Skipping frequency statistics.")
    std_mem_freq = 0
else:
    std_mem_freq = np.std(mem_freq)

# Only print statistics if we have data
if mem_used or mem_freq:
    print(f"Maximum memory used: {max_mem_used} MiB, Memory frequency std.: {std_mem_freq}")
else:
    print("No data was successfully loaded from any files.")

plt.subplots(1, 2, figsize=(2 * 7.2, 4.8))
plt.subplot(1, 2, 1)
y, x = np.histogram(mem_freq, bins=1000)
if len(mem_freq) > 0:
    cy = np.cumsum(y) / len(mem_freq)
else:
    cy = np.array([])

plt.plot(x[1:], cy)
plt.grid(True)
plt.xlabel("Memory Frequency Cont. Load [MHz]")
plt.ylabel("CDF")

folder, _ = os.path.split(args.filenames[0])
if folder.split("/")[-1].isnumeric():
    plt.legend(["Mem. Freq. capped at " + folder.split("/")[-1] + " MHz"])

plt.subplot(1, 2, 2)
plt.grid(True)
plt.plot(np.arange(0, len(mem_used)) * 1e-3, mem_used)
plt.xlabel("Time [s]")
plt.ylabel("Memory Used [MiB]")

if not args.is_short_legend:
    plt.legend(testConfig) # add info for each data
    
# plt.figure()
# plt.grid(True)
# plt.plot(np.arange(0, len(gpu_freq)) * 10e-3, gpu_freq)
# plt.xlabel("Time [s]")
# plt.ylabel("GPU Frequency [MHz]")

plt.savefig("memory.png")
# plt.show()
