# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Temperature Performance Plotting Script

This script generates a temperature-over-time plot from GPU performance measurement
data. The input json file can be generated by running the testbench using Python
interface with --measure_power option.

Expected Input File Format:
- JSON files containing GPU performance data from nvidia-smi measurements
- Each file should have the following structure:
  {
    "testConfig": {
      ...,
      "sweeps": number_of_sweeps,
      ...,
      "gpuName": "GPU Model Name",
      ...,
    },
    "XX": [  // where XX is the cell count (e.g., "08+00", "12+00", etc.)
      [sm_clock, mem_clock, power_draw, mem_used, gpu_util, mem_util, temperature],
      [sm_clock, mem_clock, power_draw, mem_used, gpu_util, mem_util, temperature],
      ...
    ]
  }

Usage:
  python temperature_plot.py --filenames file1.json --cells 8+0

Output:
- Prints min/max temperature (in the units recorded by the JSON; typically Celsius)
- Generates temperature.png with a single plot: temperature over time
"""

import argparse
import json
import os
import re

import matplotlib.pyplot as plt
import numpy as np


def main() -> None:
    """CLI entry: parse args, load JSON temperature data, and plot temperature over time.

    Parsed arguments (from base.add_argument) are available as args.filenames,
    args.cells, and args.is_short_legend.

    Args:
        filenames: List of paths to JSON files (--filenames); type List[str].
        cells: Cell count to focus on (--cells); type str.
        is_short_legend: Whether to use a short legend (--short_legend); type bool.

    Returns:
        None.

    Raises:
        SystemExit: When argparse fails (e.g. missing required --filenames or --cells).
    """
    base = argparse.ArgumentParser()
    base.add_argument(
        "--filenames",
        type=str,
        nargs="+",
        dest="filenames",
        help="Specifies the files containing the results",
        required=True,
    )
    base.add_argument(
        "--cells",
        type=str,
        dest="cells",
        help="Specifies the number of cells to focus analysis on",
        required=True,
    )
    base.add_argument(
        "--short_legend",
        action="store_true",
        default=False,
        dest="is_short_legend",
        help="whether add platform and nSlots in each legend",
    )
    args = base.parse_args()

    gpu_freq = []
    temperature = []
    test_config = []

    if "+" in args.cells:
        cells = "+".join([str(x).zfill(2) for x in args.cells.split("+")])
    else:
        cells = str(args.cells).zfill(2)

    for filename in args.filenames:
        try:
            with open(filename, "r") as ifile:
                try:
                    data = json.load(ifile)
                except json.JSONDecodeError as e:
                    print(f"Error parsing JSON from {filename}: {e}")
                    continue

                if not isinstance(data, dict):
                    print(f"Error reading {filename}: root is not a dict")
                    continue
                if cells not in data:
                    print(f"Error reading {filename}: missing key cells={cells!r}")
                    continue
                rows = data[cells]
                if not isinstance(rows, list):
                    print(f"Error reading {filename}: data[{cells!r}] is not a list")
                    continue

                for row in rows:
                    if not isinstance(row, (list, tuple)):
                        print(f"Skipping malformed row in {filename} (not list/tuple): {type(row).__name__}")
                        continue
                    if len(row) <= 6:
                        print(f"Skipping malformed row in {filename} (len={len(row)}, need > 6)")
                        continue
                    try:
                        gpu_freq.append(int(row[0]))
                        temperature.append(float(row[6]))
                    except (ValueError, TypeError) as e:
                        print(f"Skipping malformed row in {filename}: {e}")
                        continue

                # Add test config once per file, not for each data point
                test_cfg = data.get("testConfig")
                if isinstance(test_cfg, dict) and "gpuName" in test_cfg and "sweeps" in test_cfg:
                    test_config.append(
                        test_cfg["gpuName"] + " " + str(test_cfg["sweeps"]) + " slots"
                    )
        except IOError as e:
            print(f"Error opening file {filename}: {e}")
            continue
        except (KeyError, IndexError, TypeError) as e:
            print(f"Error reading temperature data from {filename} (cells={cells}): {e}")
            continue

    if not temperature:
        print("No temperature data was successfully loaded from any files.")
    else:
        min_temp = float(np.min(temperature))
        max_temp = float(np.max(temperature))
        print(f"Minimum temperature: {min_temp}, Maximum temperature: {max_temp}")

    plt.subplots(1, 2, figsize=(2 * 7.2, 4.8))

    folder, _ = os.path.split(args.filenames[0])
    plt.subplot(1, 2, 1)
    plt.grid(True)
    plt.xlabel("GPU Frequency Cont. Load [MHz]")
    plt.ylabel("CDF")

    if len(gpu_freq) > 0:
        y, x = np.histogram(gpu_freq, bins=1000)
        cy = np.cumsum(y) / len(gpu_freq)
        plt.plot(x[1:], cy)

        # Robust numeric cap from folder basename: try int(basename) then regex digits
        cap_mhz = None
        basename = os.path.basename(folder.rstrip("/"))
        try:
            cap_mhz = int(basename)
        except (ValueError, TypeError):
            match = re.search(r"\d+", basename)
            if match:
                cap_mhz = int(match.group())
        if cap_mhz is not None:
            plt.legend(["GPU Freq. capped at " + str(cap_mhz) + " MHz"])
    else:
        plt.text(0.5, 0.5, "No GPU frequency data", transform=plt.gca().transAxes,
                 ha="center", va="center", fontsize=12)

    plt.subplot(1, 2, 2)
    plt.grid(True)
    plt.plot(np.arange(0, len(temperature)) * 1e-3, temperature)
    plt.xlabel("Time [s]")
    plt.ylabel("Temperature")

    if not args.is_short_legend and test_config:
        plt.legend(test_config)

    plt.savefig("temperature.png")


if __name__ == "__main__":
    main()
